const pool = require("../db")

async function pokemonSeeder() {
    try {
        const poke = [
            {
                name: "Bulbasaur",
                description: "For some time after its birth, it uses the nutrients that are packed into the seed on its back in order to grow.",
                height: 0.7,
                weight: 6.9,
                region_id: 1,
                image: "http://localhost:3000/uploads/bulbasaur.png",
                pokedex_id: 1,
                type1: 3,
                type2: 7,
                generation: 1
            },

            {
                name: "Ivysaur",
                description: "The more sunlight Ivysaur bathes in, the more strength wells up within it, allowing the bud on its back to grow larger.",
                height: 1.0,
                weight: 13.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/ivysaur.png",
                pokedex_id: 2,
                type1: 3,
                type2: 7,
                generation: 1
            },

            {
                name: "Venusaur",
                description: "While it basks in the sun, it can convert the light into energy. As a result, it is more powerful in the summertime.",
                height: 2.0,
                weight: 100.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/venusaur.png",
                pokedex_id: 3,
                type1: 3,
                type2: 7,
                generation: 1
            },

            { name: "Charmander", description: "The flame on its tail shows the strength of its life-force. If Charmander is weak, the flame also burns weakly.", height: 0.6, weight: 8.5, region_id: 1, image: "http://localhost:3000/uploads/charmander.png", pokedex_id: 4, type1: 1, type2: null, generation: 1 },

            { name: "Charmeleon", description: "When it swings its burning tail, the temperature around it rises higher and higher, tormenting its opponents.", height: 1.1, weight: 19.0, region_id: 1, image: "http://localhost:3000/uploads/charmeleon.png", pokedex_id: 5, type1: 1, type2: null, generation: 1 },

            { name: "Charizard", description: "If Charizard becomes truly angered, the flame at the tip of its tail burns in a light blue shade.", height: 1.7, weight: 90.5, region_id: 1, image: "http://localhost:3000/uploads/charizard.png", pokedex_id: 6, type1: 1, type2: 9, generation: 1 },

            { name: "Squirtle", description: "After birth, its back swells and hardens into a shell. It sprays a potent foam from its mouth.", height: 0.5, weight: 9.0, region_id: 1, image: "http://localhost:3000/uploads/squirtle.png", pokedex_id: 7, type1: 2, type2: null, generation: 1 },

            { name: "Wartortle", description: "Wartortle’s long, furry tail is a symbol of longevity, so this Pokémon is quite popular among older people.", height: 1.0, weight: 22.5, region_id: 1, image: "http://localhost:3000/uploads/wartortle.png", pokedex_id: 8, type1: 2, type2: null, generation: 1 },

            { name: "Blastoise", description: "It deliberately increases its body weight so it can withstand the recoil of the water jets it fires.", height: 1.6, weight: 85.5, region_id: 1, image: "http://localhost:3000/uploads/blastoise.png", pokedex_id: 9, type1: 2, type2: null, generation: 1 },

            {
                name: "Caterpie",
                description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
                height: 0.3,
                weight: 2.9,
                region_id: 1,
                image: "http://localhost:3000/uploads/caterpie.png",
                pokedex_id: 10,
                type1: 11,
                type2: null,
                generation: 1
            },
            {
                name: "Metapod",
                description: "It is waiting for the moment to evolve. At this stage, it can only harden its shell to protect itself.",
                height: 0.7,
                weight: 9.9,
                region_id: 1,
                image: "http://localhost:3000/uploads/metapod.png",
                pokedex_id: 11,
                type1: 11,
                type2: null,
                generation: 1
            },
            {
                name: "Butterfree",
                description: "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
                height: 1.1,
                weight: 32.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/butterfree.png",
                pokedex_id: 12,
                type1: 11,
                type2: 9,
                generation: 1
            },
            {
                name: "Weedle",
                description: "Often found in forests, eating leaves. It has a sharp stinger on its head.",
                height: 0.3,
                weight: 3.2,
                region_id: 1,
                image: "http://localhost:3000/uploads/weedle.png",
                pokedex_id: 13,
                type1: 11,
                type2: 7,
                generation: 1
            },
            {
                name: "Kakuna",
                description: "Able to move only slightly. When endangered, it may harden its shell.",
                height: 0.6,
                weight: 10.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/kakuna.png",
                pokedex_id: 14,
                type1: 11,
                type2: 7,
                generation: 1
            },
            {
                name: "Beedrill",
                description: "Flies at high speed and attacks using the large venomous stingers on its forelegs and tail.",
                height: 1.0,
                weight: 29.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/beedrill.png",
                pokedex_id: 15,
                type1: 11,
                type2: 7,
                generation: 1
            },
            {
                name: "Pidgey",
                description: "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.",
                height: 0.3,
                weight: 1.8,
                region_id: 1,
                image: "http://localhost:3000/uploads/pidgey.png",
                pokedex_id: 16,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Pidgeotto",
                description: "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.",
                height: 1.1,
                weight: 30.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/pidgeotto.png",
                pokedex_id: 17,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Pidgeot",
                description: "When hunting, it skims the surface of water at high speed to pick off unwary prey.",
                height: 1.5,
                weight: 39.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/pidgeot.png",
                pokedex_id: 18,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Rattata",
                description: "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
                height: 0.3,
                weight: 3.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/rattata.png",
                pokedex_id: 19,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Raticate",
                description: "Its hind feet are webbed. They act as flippers, allowing it to swim in rivers and hunt for prey.",
                height: 0.7,
                weight: 18.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/raticate.png",
                pokedex_id: 20,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Spearow",
                description: "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.",
                height: 0.3,
                weight: 2.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/spearow.png",
                pokedex_id: 21,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Fearow",
                description: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
                height: 1.2,
                weight: 38.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/fearow.png",
                pokedex_id: 22,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Ekans",
                description: "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.",
                height: 2.0,
                weight: 6.9,
                region_id: 1,
                image: "http://localhost:3000/uploads/ekans.png",
                pokedex_id: 23,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Arbok",
                description: "The frightening patterns on its belly have been studied. Six variations have been confirmed.",
                height: 3.5,
                weight: 65.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/arbok.png",
                pokedex_id: 24,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Pikachu",
                description: "When several of these Pokémon gather, their electricity can cause lightning storms.",
                height: 0.4,
                weight: 6.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/pikachu.png",
                pokedex_id: 25,
                type1: 4,
                type2: null,
                generation: 1
            },
            {
                name: "Raichu",
                description: "Its long tail serves as a ground to protect itself from its own high-voltage power.",
                height: 0.8,
                weight: 30.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/raichu.png",
                pokedex_id: 26,
                type1: 4,
                type2: null,
                generation: 1
            },
            {
                name: "Sandshrew",
                description: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
                height: 0.6,
                weight: 12.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/sandshrew.png",
                pokedex_id: 27,
                type1: 8,
                type2: null,
                generation: 1
            },
            {
                name: "Sandslash",
                description: "Curls up into a spiny ball when threatened. It can roll while curled to attack or escape.",
                height: 1.0,
                weight: 29.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/sandslash.png",
                pokedex_id: 28,
                type1: 8,
                type2: null,
                generation: 1
            },
            {
                name: "Nidoran♀",
                description: "Although small, its venomous barbs make this Pokémon dangerous. The female has smaller horns.",
                height: 0.4,
                weight: 7.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/nidoranf.png",
                pokedex_id: 29,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Nidorina",
                description: "When resting deep in its burrow, its barbs always retract. This is proof that it is relaxed.",
                height: 0.8,
                weight: 20.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/nidorina.png",
                pokedex_id: 30,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Nidoqueen",
                description: "Its hard scales provide strong protection. It uses its hefty bulk to slam into opponents.",
                height: 1.3,
                weight: 60.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/nidoqueen.png",
                pokedex_id: 31,
                type1: 7,
                type2: 8,
                generation: 1
            },
            {
                name: "Nidoran♂",
                description: "It is small but its horn is filled with poison. The male has large ears and is more aggressive.",
                height: 0.5,
                weight: 9.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/nidoranm.png",
                pokedex_id: 32,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Nidorino",
                description: "Its horn is harder than diamond. It uses the horn to attack by charging straight at the foe.",
                height: 0.9,
                weight: 19.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/nidorino.png",
                pokedex_id: 33,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Nidoking",
                description: "Its steel-like tail can pack a devastating punch. It uses its bulk to crush obstacles.",
                height: 1.4,
                weight: 62.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/nidoking.png",
                pokedex_id: 34,
                type1: 7,
                type2: 8,
                generation: 1
            },
            {
                name: "Clefairy",
                description: "Its magical and cute appeal has many admirers. It is believed to be rarely seen by humans.",
                height: 0.6,
                weight: 7.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/clefairy.png",
                pokedex_id: 35,
                type1: 17,
                type2: null,
                generation: 1
            },
            {
                name: "Clefable",
                description: "A timid fairy Pokémon that is rarely seen. It runs and hides the moment it senses people.",
                height: 1.3,
                weight: 40.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/clefable.png",
                pokedex_id: 36,
                type1: 17,
                type2: null,
                generation: 1
            },
            {
                name: "Vulpix",
                description: "At the time of birth, it has just one tail. Its tail splits from the tip as it grows older.",
                height: 0.6,
                weight: 9.9,
                region_id: 1,
                image: "http://localhost:3000/uploads/vulpix.png",
                pokedex_id: 37,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Ninetales",
                description: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
                height: 1.1,
                weight: 19.9,
                region_id: 1,
                image: "http://localhost:3000/uploads/ninetales.png",
                pokedex_id: 38,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Jigglypuff",
                description: "Uses its alluring eyes to enrapture its foe. It then sings a soothing melody that lulls the foe to sleep.",
                height: 0.5,
                weight: 5.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/jigglypuff.png",
                pokedex_id: 39,
                type1: 17,
                type2: 18,
                generation: 1
            },
            {
                name: "Wigglytuff",
                description: "Its body is full of elasticity. By inhaling, it can inflate itself to an enormous size.",
                height: 1.0,
                weight: 12.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/wigglytuff.png",
                pokedex_id: 40,
                type1: 17,
                type2: 18,
                generation: 1
            },
            {
                name: "Zubat",
                description: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.",
                height: 0.8,
                weight: 7.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/zubat.png",
                pokedex_id: 41,
                type1: 7,
                type2: 9,
                generation: 1
            },
            {
                name: "Golbat",
                description: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.",
                height: 1.6,
                weight: 55.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/golbat.png",
                pokedex_id: 42,
                type1: 7,
                type2: 9,
                generation: 1
            },
            {
                name: "Oddish",
                description: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.",
                height: 0.5,
                weight: 5.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/oddish.png",
                pokedex_id: 43,
                type1: 3,
                type2: 7,
                generation: 1
            },
            {
                name: "Gloom",
                description: "Smells incredibly foul! However, around 1 out of 1,000 people enjoy sniffing its stench.",
                height: 0.8,
                weight: 8.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/gloom.png",
                pokedex_id: 44,
                type1: 3,
                type2: 7,
                generation: 1
            },
            {
                name: "Vileplume",
                description: "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.",
                height: 1.2,
                weight: 18.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/vileplume.png",
                pokedex_id: 45,
                type1: 3,
                type2: 7,
                generation: 1
            },
            {
                name: "Paras",
                description: "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.",
                height: 0.3,
                weight: 5.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/paras.png",
                pokedex_id: 46,
                type1: 11,
                type2: 3,
                generation: 1
            },
            {
                name: "Parasect",
                description: "The bug host is drained of energy by the mushroom on its back. The mushroom appears to control the bug.",
                height: 1.0,
                weight: 29.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/parasect.png",
                pokedex_id: 47,
                type1: 11,
                type2: 3,
                generation: 1
            },
            {
                name: "Venonat",
                description: "Lives in the shadows of tall trees. It is attracted by light at night.",
                height: 1.0,
                weight: 30.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/venonat.png",
                pokedex_id: 48,
                type1: 11,
                type2: 7,
                generation: 1
            },
            {
                name: "Venomoth",
                description: "The powdery scales on its wings are hard to remove. They also contain toxins.",
                height: 1.5,
                weight: 12.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/venomoth.png",
                pokedex_id: 49,
                type1: 11,
                type2: 10,
                generation: 1
            },
            {
                name: "Diglett",
                description: "Lives about one yard underground, where it feeds on plant roots. Sometimes appears above ground.",
                height: 0.2,
                weight: 0.8,
                region_id: 1,
                image: "http://localhost:3000/uploads/diglett.png",
                pokedex_id: 50,
                type1: 8,
                type2: null,
                generation: 1
            },
            {
                name: "Dugtrio",
                description: "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
                height: 0.7,
                weight: 33.3,
                region_id: 1,
                image: "http://localhost:3000/uploads/dugtrio.png",
                pokedex_id: 51,
                type1: 8,
                type2: null,
                generation: 1
            },
            {
                name: "Meowth",
                description: "Adores circular objects. It wanders the streets on a nightly basis to look for dropped loose change.",
                height: 0.4,
                weight: 4.2,
                region_id: 1,
                image: "http://localhost:3000/uploads/meowth.png",
                pokedex_id: 52,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Persian",
                description: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle, vicious temperament.",
                height: 1.0,
                weight: 32.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/persian.png",
                pokedex_id: 53,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Psyduck",
                description: "While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.",
                height: 0.8,
                weight: 19.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/psyduck.png",
                pokedex_id: 54,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Golduck",
                description: "Often seen swimming elegantly by lakeshores. It is often mistaken for the Japanese mythical creature kappa.",
                height: 1.7,
                weight: 76.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/golduck.png",
                pokedex_id: 55,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Mankey",
                description: "Extremely quick to anger. It could be docile one moment, then thrashing away the next instant.",
                height: 0.5,
                weight: 28.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/mankey.png",
                pokedex_id: 56,
                type1: 6,
                type2: null,
                generation: 1
            },
            {
                name: "Primeape",
                description: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.",
                height: 1.0,
                weight: 32.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/primeape.png",
                pokedex_id: 57,
                type1: 6,
                type2: null,
                generation: 1
            },
            {
                name: "Growlithe",
                description: "Very friendly and faithful to people. It will bark fiercely at anything that intrudes on its territory.",
                height: 0.7,
                weight: 19.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/growlithe.png",
                pokedex_id: 58,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Arcanine",
                description: "A legendary Pokémon in China. Many people are charmed by its grace and beauty while running.",
                height: 1.9,
                weight: 155.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/arcanine.png",
                pokedex_id: 59,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Poliwag",
                description: "Its newly grown legs prevent it from running. It appears to prefer swimming over trying to stand.",
                height: 0.6,
                weight: 12.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/poliwag.png",
                pokedex_id: 60,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Poliwhirl",
                description: "Capable of living in or out of water. Its skin is covered by a thin, slippery film.",
                height: 1.0,
                weight: 20.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/poliwhirl.png",
                pokedex_id: 61,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Poliwrath",
                description: "An adept swimmer at both the front crawl and breaststroke. It can easily overtake the best human swimmers.",
                height: 1.3,
                weight: 54.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/poliwrath.png",
                pokedex_id: 62,
                type1: 2,
                type2: 6,
                generation: 1
            },
            {
                name: "Abra",
                description: "Sleeps 18 hours a day. Even while asleep, it can manipulate its surroundings using telekinesis.",
                height: 0.9,
                weight: 19.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/abra.png",
                pokedex_id: 63,
                type1: 10,
                type2: null,
                generation: 1
            },
            {
                name: "Kadabra",
                description: "It emits special alpha waves from its body that induce headaches just by being close by.",
                height: 1.3,
                weight: 56.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/kadabra.png",
                pokedex_id: 64,
                type1: 10,
                type2: null,
                generation: 1
            },
            {
                name: "Alakazam",
                description: "Its brain continually grows, making its head far too heavy to support with its neck.",
                height: 1.5,
                weight: 48.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/alakazam.png",
                pokedex_id: 65,
                type1: 10,
                type2: null,
                generation: 1
            },
            {
                name: "Machop",
                description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
                height: 0.8,
                weight: 19.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/machop.png",
                pokedex_id: 66,
                type1: 6,
                type2: null,
                generation: 1
            },
            {
                name: "Machoke",
                description: "Its muscular body is so powerful that it must wear a power-save belt to regulate its motions.",
                height: 1.5,
                weight: 70.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/machoke.png",
                pokedex_id: 67,
                type1: 6,
                type2: null,
                generation: 1
            },
            {
                name: "Machamp",
                description: "Using its heavy muscles, it throws powerful punches that can send its victims clear over the horizon.",
                height: 1.6,
                weight: 130.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/machamp.png",
                pokedex_id: 68,
                type1: 6,
                type2: null,
                generation: 1
            },
            {
                name: "Bellsprout",
                description: "Prefers hot and humid places. It ensnares tiny insects with its vines and devours them.",
                height: 0.7,
                weight: 4.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/bellsprout.png",
                pokedex_id: 69,
                type1: 3,
                type2: 7,
                generation: 1
            },
            {
                name: "Weepinbell",
                description: "When hungry, it swallows anything that moves. Its hunger is never satisfied.",
                height: 1.0,
                weight: 6.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/weepinbell.png",
                pokedex_id: 70,
                type1: 3,
                type2: 7,
                generation: 1
            },
            {
                name: "Victreebel",
                description: "Said to live in huge colonies deep in jungles, although no one has ever returned from there.",
                height: 1.7,
                weight: 15.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/victreebel.png",
                pokedex_id: 71,
                type1: 3,
                type2: 7,
                generation: 1
            },
            {
                name: "Tentacool",
                description: "Drifts in shallow seas. Anglers who hook them are often poisoned by their stingers.",
                height: 0.9,
                weight: 45.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/tentacool.png",
                pokedex_id: 72,
                type1: 2,
                type2: 7,
                generation: 1
            },
            {
                name: "Tentacruel",
                description: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.",
                height: 1.6,
                weight: 55.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/tentacruel.png",
                pokedex_id: 73,
                type1: 2,
                type2: 7,
                generation: 1
            },
            {
                name: "Geodude",
                description: "Found in fields and mountains. Mistaking them for boulders has made many hikers stumble.",
                height: 0.4,
                weight: 20.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/geodude.png",
                pokedex_id: 74,
                type1: 12,
                type2: 8,
                generation: 1
            },
            {
                name: "Graveler",
                description: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing direction.",
                height: 1.0,
                weight: 105.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/graveler.png",
                pokedex_id: 75,
                type1: 12,
                type2: 8,
                generation: 1
            },
            {
                name: "Golem",
                description: "Its body can withstand even dynamite blasts. It rolls down mountain paths at high speed.",
                height: 1.4,
                weight: 300.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/golem.png",
                pokedex_id: 76,
                type1: 12,
                type2: 8,
                generation: 1
            },
            {
                name: "Ponyta",
                description: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.",
                height: 1.0,
                weight: 30.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/ponyta.png",
                pokedex_id: 77,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Rapidash",
                description: "Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it.",
                height: 1.7,
                weight: 95.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/rapidash.png",
                pokedex_id: 78,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Slowpoke",
                description: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.",
                height: 1.2,
                weight: 36.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/slowpoke.png",
                pokedex_id: 79,
                type1: 2,
                type2: 10,
                generation: 1
            },
            {
                name: "Slowbro",
                description: "The Shellder that latches onto its tail is said to feed on the host’s left-over scraps.",
                height: 1.6,
                weight: 78.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/slowbro.png",
                pokedex_id: 80,
                type1: 2,
                type2: 10,
                generation: 1
            },
            {
                name: "Magnemite",
                description: "Uses anti-gravity to stay suspended. Appears without warning.",
                height: 0.3,
                weight: 6.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/magnemite.png",
                pokedex_id: 81,
                type1: 16,
                type2: 4,
                generation: 1
            },
            {
                name: "Magneton",
                description: "Formed by several Magnemite linked together. Emits powerful magnetic waves.",
                height: 1.0,
                weight: 60.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/magneton.png",
                pokedex_id: 82,
                type1: 16,
                type2: 4,
                generation: 1
            },
            {
                name: "Farfetch’d",
                description: "Lives where reedy plants grow. It uses a stalk as a weapon.",
                height: 0.8,
                weight: 15.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/farfetchd.png",
                pokedex_id: 83,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Doduo",
                description: "A bird Pokémon with two heads. The heads fight each other.",
                height: 1.4,
                weight: 39.2,
                region_id: 1,
                image: "http://localhost:3000/uploads/doduo.png",
                pokedex_id: 84,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Dodrio",
                description: "One head sleeps, the other two are awake. Very vigilant.",
                height: 1.8,
                weight: 85.2,
                region_id: 1,
                image: "http://localhost:3000/uploads/dodrio.png",
                pokedex_id: 85,
                type1: 18,
                type2: 9,
                generation: 1
            },
            {
                name: "Seel",
                description: "Loves freezing cold conditions. Enjoys swimming in frigid water.",
                height: 1.1,
                weight: 90.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/seel.png",
                pokedex_id: 86,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Dewgong",
                description: "Stores thermal energy in its body. Sleek and warm to the touch.",
                height: 1.7,
                weight: 120.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/dewgong.png",
                pokedex_id: 87,
                type1: 2,
                type2: 5,
                generation: 1
            },
            {
                name: "Grimer",
                description: "Made of living sludge. Emits a stench that is overpowering.",
                height: 0.9,
                weight: 30.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/grimer.png",
                pokedex_id: 88,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Muk",
                description: "Smells so awful it can cause fainting. Thickly covered in sludge.",
                height: 1.2,
                weight: 30.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/muk.png",
                pokedex_id: 89,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Shellder",
                description: "Its hard shell protects its soft body. Clamps down on prey.",
                height: 0.3,
                weight: 4.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/shellder.png",
                pokedex_id: 90,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Cloyster",
                description: "Its shell is harder than diamonds. It attacks with spikes.",
                height: 1.5,
                weight: 132.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/cloyster.png",
                pokedex_id: 91,
                type1: 2,
                type2: 5,
                generation: 1
            },
            {
                name: "Gastly",
                description: "Almost invisible. Made of gas. Can topple an Indian elephant.",
                height: 1.3,
                weight: 0.1,
                region_id: 1,
                image: "http://localhost:3000/uploads/gastly.png",
                pokedex_id: 92,
                type1: 13,
                type2: 7,
                generation: 1
            },
            {
                name: "Haunter",
                description: "Because it waves its hands, it causes an eerie chill.",
                height: 1.6,
                weight: 0.1,
                region_id: 1,
                image: "http://localhost:3000/uploads/haunter.png",
                pokedex_id: 93,
                type1: 13,
                type2: 7,
                generation: 1
            },
            {
                name: "Gengar",
                description: "Under a full moon, it mimics shadows and steals life force.",
                height: 1.5,
                weight: 40.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/gengar.png",
                pokedex_id: 94,
                type1: 13,
                type2: 7,
                generation: 1
            },
            {
                name: "Onix",
                description: "A rock snake that burrows at high speed. Its body is hard as bedrock.",
                height: 8.8,
                weight: 210.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/onix.png",
                pokedex_id: 95,
                type1: 12,
                type2: 8,
                generation: 1
            },
            {
                name: "Drowzee",
                description: "Puts enemies to sleep by hypnotizing them.",
                height: 1.0,
                weight: 32.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/drowzee.png",
                pokedex_id: 96,
                type1: 10,
                type2: null,
                generation: 1
            },
            {
                name: "Hypno",
                description: "Carries a pendulum-like device. Can put others to sleep.",
                height: 1.6,
                weight: 75.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/hypno.png",
                pokedex_id: 97,
                type1: 10,
                type2: null,
                generation: 1
            },
            {
                name: "Krabby",
                description: "Its pincers are superb weapons. Lives on beaches.",
                height: 0.4,
                weight: 6.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/krabby.png",
                pokedex_id: 98,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Kingler",
                description: "One claw grew massively. Its power is tremendous.",
                height: 1.3,
                weight: 60.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/kingler.png",
                pokedex_id: 99,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Voltorb",
                description: "Often mistaken for a Poké Ball. Has a tendency to explode.",
                height: 0.5,
                weight: 10.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/voltorb.png",
                pokedex_id: 100,
                type1: 4,
                type2: null,
                generation: 1
            },
            {
                name: "Electrode",
                description: "It stores electrical energy inside its body. It explodes at the slightest provocation.",
                height: 1.2,
                weight: 66.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/electrode.png",
                pokedex_id: 101,
                type1: 4,
                type2: null,
                generation: 1
            },
            {
                name: "Exeggcute",
                description: "Though it may look like eggs, it is actually a Pokémon. It clusters in a six-pack.",
                height: 0.4,
                weight: 2.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/exeggcute.png",
                pokedex_id: 102,
                type1: 3,
                type2: 10,
                generation: 1
            },
            {
                name: "Exeggutor",
                description: "Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute.",
                height: 2.0,
                weight: 120.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/exeggutor.png",
                pokedex_id: 103,
                type1: 3,
                type2: 10,
                generation: 1
            },
            {
                name: "Cubone",
                description: "Wears the skull of its deceased mother. Its cries echo within the skull.",
                height: 0.4,
                weight: 6.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/cubone.png",
                pokedex_id: 104,
                type1: 8,
                type2: null,
                generation: 1
            },
            {
                name: "Marowak",
                description: "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang.",
                height: 1.0,
                weight: 45.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/marowak.png",
                pokedex_id: 105,
                type1: 8,
                type2: null,
                generation: 1
            },
            {
                name: "Hitmonlee",
                description: "Its legs freely stretch and contract. It is known for its mastery of kicking attacks.",
                height: 1.5,
                weight: 49.8,
                region_id: 1,
                image: "http://localhost:3000/uploads/hitmonlee.png",
                pokedex_id: 106,
                type1: 6,
                type2: null,
                generation: 1
            },
            {
                name: "Hitmonchan",
                description: "Its punches slice through the air at high velocity. It specializes in boxing moves.",
                height: 1.4,
                weight: 50.2,
                region_id: 1,
                image: "http://localhost:3000/uploads/hitmonchan.png",
                pokedex_id: 107,
                type1: 6,
                type2: null,
                generation: 1
            },
            {
                name: "Lickitung",
                description: "Its long tongue is always slobbering. The saliva contains a numbing agent.",
                height: 1.2,
                weight: 65.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/lickitung.png",
                pokedex_id: 108,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Koffing",
                description: "Its body is full of poisonous gas. It floats into garbage dumps seeking scraps.",
                height: 0.6,
                weight: 1.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/koffing.png",
                pokedex_id: 109,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Weezing",
                description: "It mixes gases within its body. The more toxic the gas, the sweeter the smell.",
                height: 1.2,
                weight: 9.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/weezing.png",
                pokedex_id: 110,
                type1: 7,
                type2: null,
                generation: 1
            },
            {
                name: "Rhyhorn",
                description: "A Pokémon with a one-track mind. It charges directly ahead, destroying everything.",
                height: 1.0,
                weight: 115.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/rhyhorn.png",
                pokedex_id: 111,
                type1: 12,
                type2: 8,
                generation: 1
            },
            {
                name: "Rhydon",
                description: "Protected by armor-like hide. It can punch holes through boulders with its horn.",
                height: 1.9,
                weight: 120.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/rhydon.png",
                pokedex_id: 112,
                type1: 12,
                type2: 8,
                generation: 1
            },
            {
                name: "Chansey",
                description: "Its egg is nutritious and delicious. It lays several eggs a day.",
                height: 1.1,
                weight: 34.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/chansey.png",
                pokedex_id: 113,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Tangela",
                description: "Its body is wrapped in blue vines. Even if the vines are torn off, they grow back overnight.",
                height: 1.0,
                weight: 35.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/tangela.png",
                pokedex_id: 114,
                type1: 3,
                type2: null,
                generation: 1
            },
            {
                name: "Kangaskhan",
                description: "Raises its young in its belly pouch. The baby rarely ventures outside until it is fully grown.",
                height: 2.2,
                weight: 80.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/kangaskhan.png",
                pokedex_id: 115,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Horsea",
                description: "If it senses danger, it sprays ink to escape and hides itself among coral.",
                height: 0.4,
                weight: 8.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/horsea.png",
                pokedex_id: 116,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Seadra",
                description: "The spines covering its body are highly poisonous. It blends with seaweed.",
                height: 1.2,
                weight: 25.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/seadra.png",
                pokedex_id: 117,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Goldeen",
                description: "Its tail fin billows like an elegant ballroom dress. It is known as the Water Queen.",
                height: 0.6,
                weight: 15.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/goldeen.png",
                pokedex_id: 118,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Seaking",
                description: "During mating season, it patrols rivers tirelessly in search of a partner.",
                height: 1.3,
                weight: 39.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/seaking.png",
                pokedex_id: 119,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Staryu",
                description: "If its body is torn, it can regenerate limbs. The core shines brightly at night.",
                height: 0.8,
                weight: 34.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/staryu.png",
                pokedex_id: 120,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Starmie",
                description: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.",
                height: 1.1,
                weight: 80.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/starmie.png",
                pokedex_id: 121,
                type1: 2,
                type2: 10,
                generation: 1
            },
            {
                name: "Mr. Mime",
                description: "If interrupted in the middle of miming, it will slap around the offender with its broad hands.",
                height: 1.3,
                weight: 54.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/mr-mime.png",
                pokedex_id: 122,
                type1: 10,
                type2: 17,
                generation: 1
            },
            {
                name: "Scyther",
                description: "With ninja-like agility and speed, it can create the illusion of multiple copies of itself.",
                height: 1.5,
                weight: 56.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/scyther.png",
                pokedex_id: 123,
                type1: 11,
                type2: 9,
                generation: 1
            },
            {
                name: "Jynx",
                description: "It seductively wiggles its hips as it walks. It can cause people to dance uncontrollably.",
                height: 1.4,
                weight: 40.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/jynx.png",
                pokedex_id: 124,
                type1: 5,
                type2: 10,
                generation: 1
            },
            {
                name: "Electabuzz",
                description: "It loves to feed on strong electricity. It occasionally appears around power plants.",
                height: 1.1,
                weight: 30.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/electabuzz.png",
                pokedex_id: 125,
                type1: 4,
                type2: null,
                generation: 1
            },
            {
                name: "Magmar",
                description: "Born in the crater of a volcano. Its body is always cloaked in flames.",
                height: 1.3,
                weight: 44.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/magmar.png",
                pokedex_id: 126,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Pinsir",
                description: "Grips prey in its pincers and tears them apart with brute force.",
                height: 1.5,
                weight: 55.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/pinsir.png",
                pokedex_id: 127,
                type1: 11,
                type2: null,
                generation: 1
            },
            {
                name: "Tauros",
                description: "A rowdy Pokémon with a lot of stamina. Once it starts charging, it stops for nothing.",
                height: 1.4,
                weight: 88.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/tauros.png",
                pokedex_id: 128,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Magikarp",
                description: "It is virtually worthless in terms of power, but it evolves into the almighty Gyarados.",
                height: 0.9,
                weight: 10.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/magikarp.png",
                pokedex_id: 129,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Gyarados",
                description: "Rarely seen in the wild. Its temper is legendary and it goes on rampages.",
                height: 6.5,
                weight: 235.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/gyarados.png",
                pokedex_id: 130,
                type1: 2,
                type2: 9,
                generation: 1
            },
            {
                name: "Lapras",
                description: "A gentle soul. It ferries people across water using its long neck and shell.",
                height: 2.5,
                weight: 220.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/lapras.png",
                pokedex_id: 131,
                type1: 2,
                type2: 5,
                generation: 1
            },
            {
                name: "Ditto",
                description: "Capable of copying an enemy’s genetic code to instantly transform into a duplicate.",
                height: 0.3,
                weight: 4.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/ditto.png",
                pokedex_id: 132,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Eevee",
                description: "Its genetic makeup is unstable, allowing it to evolve into many different forms.",
                height: 0.3,
                weight: 6.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/eevee.png",
                pokedex_id: 133,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Vaporeon",
                description: "Lives close to water. Its body structure allows it to melt into the water.",
                height: 1.0,
                weight: 29.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/vaporeon.png",
                pokedex_id: 134,
                type1: 2,
                type2: null,
                generation: 1
            },
            {
                name: "Jolteon",
                description: "Its fur has sharp needles that create electricity as it moves.",
                height: 0.8,
                weight: 24.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/jolteon.png",
                pokedex_id: 135,
                type1: 4,
                type2: null,
                generation: 1
            },
            {
                name: "Flareon",
                description: "Stores thermal energy in its body. Its temperature can rise to 900°C.",
                height: 0.9,
                weight: 25.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/flareon.png",
                pokedex_id: 136,
                type1: 1,
                type2: null,
                generation: 1
            },
            {
                name: "Porygon",
                description: "Created using the latest technology. It can freely travel within cyberspace.",
                height: 0.8,
                weight: 36.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/porygon.png",
                pokedex_id: 137,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Omanyte",
                description: "A prehistoric Pokémon revived from a fossil using modern science.",
                height: 0.4,
                weight: 7.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/omanyte.png",
                pokedex_id: 138,
                type1: 2,
                type2: 12,
                generation: 1
            },
            {
                name: "Omastar",
                description: "Its tentacles are extremely powerful. It uses them to ensnare prey.",
                height: 1.0,
                weight: 35.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/omastar.png",
                pokedex_id: 139,
                type1: 2,
                type2: 12,
                generation: 1
            },
            {
                name: "Kabuto",
                description: "A Pokémon resurrected from a fossil. It uses a hard shell to protect itself.",
                height: 0.5,
                weight: 11.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/kabuto.png",
                pokedex_id: 140,
                type1: 2,
                type2: 12,
                generation: 1
            },
            {
                name: "Kabutops",
                description: "Its sleek shape allows it to swim at high speed while slicing prey with its arms.",
                height: 1.3,
                weight: 40.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/kabutops.png",
                pokedex_id: 141,
                type1: 2,
                type2: 12,
                generation: 1
            },
            {
                name: "Aerodactyl",
                description: "A savage Pokémon resurrected from genetic material extracted from amber.",
                height: 1.8,
                weight: 59.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/aerodactyl.png",
                pokedex_id: 142,
                type1: 12,
                type2: 9,
                generation: 1
            },
            {
                name: "Snorlax",
                description: "Will eat anything, even if it is a little moldy. It sleeps most of the time.",
                height: 2.1,
                weight: 460.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/snorlax.png",
                pokedex_id: 143,
                type1: 18,
                type2: null,
                generation: 1
            },
            {
                name: "Articuno",
                description: "A legendary bird Pokémon. It can freeze moisture in the air to create snow.",
                height: 1.7,
                weight: 55.4,
                region_id: 1,
                image: "http://localhost:3000/uploads/articuno.png",
                pokedex_id: 144,
                type1: 5,
                type2: 9,
                generation: 1
            },
            {
                name: "Zapdos",
                description: "A legendary bird Pokémon said to appear when the sky turns dark with lightning.",
                height: 1.6,
                weight: 52.6,
                region_id: 1,
                image: "http://localhost:3000/uploads/zapdos.png",
                pokedex_id: 145,
                type1: 4,
                type2: 9,
                generation: 1
            },
            {
                name: "Moltres",
                description: "A legendary bird Pokémon. Its appearance indicates the coming of spring.",
                height: 2.0,
                weight: 60.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/moltres.png",
                pokedex_id: 146,
                type1: 1,
                type2: 9,
                generation: 1
            },
            {
                name: "Dratini",
                description: "Long considered a myth. It keeps growing larger as it sheds its skin repeatedly.",
                height: 1.8,
                weight: 3.3,
                region_id: 1,
                image: "http://localhost:3000/uploads/dratini.png",
                pokedex_id: 147,
                type1: 14,
                type2: null,
                generation: 1
            },
            {
                name: "Dragonair",
                description: "A mystical Pokémon that exudes an aura capable of preserving the weather.",
                height: 4.0,
                weight: 16.5,
                region_id: 1,
                image: "http://localhost:3000/uploads/dragonair.png",
                pokedex_id: 148,
                type1: 14,
                type2: null,
                generation: 1
            },
            {
                name: "Dragonite",
                description: "It can circle the globe in just 16 hours. A kindhearted Pokémon often rescuing people.",
                height: 2.2,
                weight: 210.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/dragonite.png",
                pokedex_id: 149,
                type1: 14,
                type2: 9,
                generation: 1
            },
            {
                name: "Mewtwo",
                description: "It was created by a scientist after years of horrific gene-splicing experiments.",
                height: 2.0,
                weight: 122.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/mewtwo.png",
                pokedex_id: 150,
                type1: 10,
                type2: null,
                generation: 1
            },
            {
                name: "Mew",
                description: "So rare that it is still said to be a mirage. It can learn any move.",
                height: 0.4,
                weight: 4.0,
                region_id: 1,
                image: "http://localhost:3000/uploads/mew.png",
                pokedex_id: 151,
                type1: 10,
                type2: null,
                generation: 1
            },

        ]

        for (let pokemon of poke) {
            await pool.query(`
                INSERT INTO pokemon (name, description, height, weight, region_id, image, pokedex_id, type1, type2, generation) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT (name) DO NOTHING`,
                [pokemon.name, pokemon.description, pokemon.height, pokemon.weight, pokemon.region_id, pokemon.image, pokemon.pokedex_id, pokemon.type1, pokemon.type2, pokemon.generation])
        }

        console.log("Berhasil Membuat Pokemon")
    }
    catch (err) {
        console.log("Gagal Membuat Pokemon, Error: ", err.message)
    }
    finally {
        process.exit(0)
    }
}

module.exports = pokemonSeeder