const pool = require("../../db")

async function pokemonGen5Seeder() {
    try {
        const poke = [
            {
                name: "Victini",
                description: "This Pokémon brings victory. It is said that Trainers with Victini always win.",
                height: 0.4,
                weight: 4.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/victini.png",
                pokedex_id: 494,
                type1: 1,
                type2: 10,
                generation: 5
            },
            {
                name: "Snivy",
                description: "It is very intelligent and calm. Being exposed to lots of sunlight makes its movements swifter.",
                height: 0.6,
                weight: 8.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/snivy.png",
                pokedex_id: 495,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Servine",
                description: "When it gets dirty, its leaves can't be used in photosynthesis, so it always keeps itself clean.",
                height: 0.8,
                weight: 16.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/servine.png",
                pokedex_id: 496,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Serperior",
                description: "It only gives its all against strong opponents. It stays calm even when it is in trouble.",
                height: 3.3,
                weight: 63.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/serperior.png",
                pokedex_id: 497,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Tepig",
                description: "It blows fire from its snout. Its body gets hotter as the flame burns brighter.",
                height: 0.5,
                weight: 9.9,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/tepig.png",
                pokedex_id: 498,
                type1: 1,
                type2: null,
                generation: 5
            },
            {
                name: "Pignite",
                description: "The more it eats, the more fuel it has to make the fire in its stomach stronger.",
                height: 1.0,
                weight: 55.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/pignite.png",
                pokedex_id: 499,
                type1: 1,
                type2: 6,
                generation: 5
            },
            {
                name: "Emboar",
                description: "It can throw a fire punch by setting its fists ablaze with its fiery chin beard.",
                height: 1.6,
                weight: 150.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/emboar.png",
                pokedex_id: 500,
                type1: 1,
                type2: 6,
                generation: 5
            },
            {
                name: "Oshawott",
                description: "It uses its scalchop to perform various attacks. The scalchop can be re-grown if damaged.",
                height: 0.5,
                weight: 5.9,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/oshawott.png",
                pokedex_id: 501,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Dewott",
                description: "Strict training is how it learns its flowing double-scalchop technique.",
                height: 0.8,
                weight: 24.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/dewott.png",
                pokedex_id: 502,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Samurott",
                description: "One swing of its horn blade can cleave an ocean wave in two.",
                height: 1.5,
                weight: 94.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/samurott.png",
                pokedex_id: 503,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Patrat",
                description: "Using food stored in cheek pouches, they can keep watch for days.",
                height: 0.5,
                weight: 11.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/patrat.png",
                pokedex_id: 504,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Watchog",
                description: "When they see an enemy, their tails stand high and flash brightly.",
                height: 1.1,
                weight: 27.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/watchog.png",
                pokedex_id: 505,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Lillipup",
                description: "It faces strong opponents with great courage, despite being tiny.",
                height: 0.4,
                weight: 4.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/lillipup.png",
                pokedex_id: 506,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Herdier",
                description: "It develops a loyal personality, protecting its trainer with devotion.",
                height: 0.9,
                weight: 14.7,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/herdier.png",
                pokedex_id: 507,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Stoutland",
                description: "Intelligent and extremely trustworthy, it rescues people lost at sea.",
                height: 1.2,
                weight: 61.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/stoutland.png",
                pokedex_id: 508,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Purrloin",
                description: "Their cute act is a ruse. They steal from people just for fun.",
                height: 0.4,
                weight: 10.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/purrloin.png",
                pokedex_id: 509,
                type1: 15,
                type2: null,
                generation: 5
            },
            {
                name: "Liepard",
                description: "It moves silently and strikes without warning.",
                height: 1.1,
                weight: 37.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/liepard.png",
                pokedex_id: 510,
                type1: 15,
                type2: null,
                generation: 5
            },
            {
                name: "Pansage",
                description: "It shares the leaves on its head with those in need.",
                height: 0.6,
                weight: 10.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/pansage.png",
                pokedex_id: 511,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Simisage",
                description: "It attacks enemies with the spiky leaves on its head.",
                height: 1.1,
                weight: 30.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/simisage.png",
                pokedex_id: 512,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Pansear",
                description: "It likes to help people. It can heat rocks to warm others.",
                height: 0.6,
                weight: 11.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/pansear.png",
                pokedex_id: 513,
                type1: 1,
                type2: null,
                generation: 5
            },
            {
                name: "Simisear",
                description: "It loves sugary foods. It stores fire energy inside its body.",
                height: 1.0,
                weight: 28.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/simisear.png",
                pokedex_id: 514,
                type1: 1,
                type2: null,
                generation: 5
            },
            {
                name: "Panpour",
                description: "It stores water in its head fur. This water is soft and ideal for washing.",
                height: 0.6,
                weight: 13.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/panpour.png",
                pokedex_id: 515,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Simipour",
                description: "It can shoot high-pressure water from its tail.",
                height: 1.0,
                weight: 29.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/simipour.png",
                pokedex_id: 516,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Munna",
                description: "Munna eats dreams and emits a dreamy mist.",
                height: 0.6,
                weight: 23.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/munna.png",
                pokedex_id: 517,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Musharna",
                description: "The mist it releases is filled with dreams.",
                height: 1.1,
                weight: 60.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/musharna.png",
                pokedex_id: 518,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Pidove",
                description: "Its sense of direction is poor, but it is very friendly.",
                height: 0.3,
                weight: 2.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/pidove.png",
                pokedex_id: 519,
                type1: 18,
                type2: 9,
                generation: 5
            },
            {
                name: "Tranquill",
                description: "It never gets confused, even in complicated cities.",
                height: 0.6,
                weight: 15.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/tranquill.png",
                pokedex_id: 520,
                type1: 18,
                type2: 9,
                generation: 5
            },
            {
                name: "Unfezant",
                description: "Males swing their long neck feathers to threaten rivals.",
                height: 1.2,
                weight: 29.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/unfezant.png",
                pokedex_id: 521,
                type1: 18,
                type2: 9,
                generation: 5
            },
            {
                name: "Blitzle",
                description: "Its mane shines when it discharges electricity.",
                height: 0.8,
                weight: 29.8,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/blitzle.png",
                pokedex_id: 522,
                type1: 4,
                type2: null,
                generation: 5
            },
            {
                name: "Zebstrika",
                description: "They gallop at high speeds and shoot lightning from their manes.",
                height: 1.6,
                weight: 79.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/zebstrika.png",
                pokedex_id: 523,
                type1: 4,
                type2: null,
                generation: 5
            },
            {
                name: "Roggenrola",
                description: "It was found in a fissure in a layer of exposed rock.",
                height: 0.4,
                weight: 18.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/roggenrola.png",
                pokedex_id: 524,
                type1: 12,
                type2: null,
                generation: 5
            },
            {
                name: "Boldore",
                description: "It relies on sound to know what is around it.",
                height: 0.9,
                weight: 102.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/boldore.png",
                pokedex_id: 525,
                type1: 12,
                type2: null,
                generation: 5
            },
            {
                name: "Gigalith",
                description: "Compressing the energy from its core, it shoots powerful beams.",
                height: 1.7,
                weight: 260.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/gigalith.png",
                pokedex_id: 526,
                type1: 12,
                type2: null,
                generation: 5
            },
            {
                name: "Woobat",
                description: "The suction from its nose leaves heart-shaped marks.",
                height: 0.4,
                weight: 2.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/woobat.png",
                pokedex_id: 527,
                type1: 10,
                type2: 9,
                generation: 5
            },
            {
                name: "Swoobat",
                description: "It emits sound waves powerful enough to demolish concrete.",
                height: 0.9,
                weight: 10.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/swoobat.png",
                pokedex_id: 528,
                type1: 10,
                type2: 9,
                generation: 5
            },
            {
                name: "Drilbur",
                description: "It can dig through the ground at a speed of over 100 km/h.",
                height: 0.3,
                weight: 8.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/drilbur.png",
                pokedex_id: 529,
                type1: 8,
                type2: null,
                generation: 5
            },
            {
                name: "Excadrill",
                description: "Its steel claws can cut through iron beams with ease.",
                height: 0.7,
                weight: 40.4,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/excadrill.png",
                pokedex_id: 530,
                type1: 8,
                type2: 16,
                generation: 5
            },
            {
                name: "Audino",
                description: "Its hearing is so good that it can sense a person's emotions.",
                height: 1.1,
                weight: 31.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/audino.png",
                pokedex_id: 531,
                type1: 18,
                type2: 17,
                generation: 5
            },
            {
                name: "Timburr",
                description: "Always carrying a wooden beam, it trains its muscles daily.",
                height: 0.6,
                weight: 12.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/timburr.png",
                pokedex_id: 532,
                type1: 6,
                type2: null,
                generation: 5
            },
            {
                name: "Gurdurr",
                description: "The steel beam it carries proves its strength.",
                height: 1.2,
                weight: 40.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/gurdurr.png",
                pokedex_id: 533,
                type1: 6,
                type2: null,
                generation: 5
            },
            {
                name: "Conkeldurr",
                description: "It uses concrete pillars as weapons with masterful skill.",
                height: 1.4,
                weight: 87.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/conkeldurr.png",
                pokedex_id: 534,
                type1: 6,
                type2: null,
                generation: 5
            },
            {
                name: "Tympole",
                description: "It vibrates its cheeks to communicate with others underwater.",
                height: 0.5,
                weight: 4.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/tympole.png",
                pokedex_id: 535,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Palpitoad",
                description: "It can amplify vibrations through its body to attack enemies.",
                height: 0.8,
                weight: 17.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/palpitoad.png",
                pokedex_id: 536,
                type1: 2,
                type2: 8,
                generation: 5
            },
            {
                name: "Seismitoad",
                description: "It creates vibrations strong enough to topple buildings.",
                height: 1.5,
                weight: 62.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/seismitoad.png",
                pokedex_id: 537,
                type1: 2,
                type2: 8,
                generation: 5
            },
            {
                name: "Throh",
                description: "It never lets go once it grabs its opponent.",
                height: 1.3,
                weight: 55.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/throh.png",
                pokedex_id: 538,
                type1: 6,
                type2: null,
                generation: 5
            },
            {
                name: "Sawk",
                description: "It trains constantly, breaking boulders as part of its regimen.",
                height: 1.4,
                weight: 51.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/sawk.png",
                pokedex_id: 539,
                type1: 6,
                type2: null,
                generation: 5
            },
            {
                name: "Sewaddle",
                description: "It makes warm clothes for itself out of leaves.",
                height: 0.3,
                weight: 2.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/sewaddle.png",
                pokedex_id: 540,
                type1: 11,
                type2: 3,
                generation: 5
            },
            {
                name: "Swadloon",
                description: "It protects itself from the cold by wrapping in leaves sewn with silk.",
                height: 0.5,
                weight: 7.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/swadloon.png",
                pokedex_id: 541,
                type1: 11,
                type2: 3,
                generation: 5
            },
            {
                name: "Leavanny",
                description: "A caring Pokémon that makes clothes for small Pokémon with its cutters.",
                height: 1.2,
                weight: 20.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/leavanny.png",
                pokedex_id: 542,
                type1: 11,
                type2: 3,
                generation: 5
            },
            {
                name: "Venipede",
                description: "It discovers what is going on around it by using the feelers on its head and tail.",
                height: 0.4,
                weight: 5.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/venipede.png",
                pokedex_id: 543,
                type1: 11,
                type2: 7,
                generation: 5
            },
            {
                name: "Whirlipede",
                description: "It crushes foes with its heavy body while protected by its hard shell.",
                height: 1.2,
                weight: 58.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/whirlipede.png",
                pokedex_id: 544,
                type1: 11,
                type2: 7,
                generation: 5
            },
            {
                name: "Scolipede",
                description: "With quick movements, it chomps foes with its poisonous, giant horns.",
                height: 2.5,
                weight: 200.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/scolipede.png",
                pokedex_id: 545,
                type1: 11,
                type2: 7,
                generation: 5
            },
            {
                name: "Cottonee",
                description: "When attacked, it escapes by spinning its body and floating on the wind.",
                height: 0.3,
                weight: 0.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/cottonee.png",
                pokedex_id: 546,
                type1: 3,
                type2: 17,
                generation: 5
            },
            {
                name: "Whimsicott",
                description: "It scatters cotton-like spores that cause chaos wherever they land.",
                height: 0.7,
                weight: 6.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/whimsicott.png",
                pokedex_id: 547,
                type1: 3,
                type2: 17,
                generation: 5
            },
            {
                name: "Petilil",
                description: "The leaves on its head are very bitter, but eating them is healthy.",
                height: 0.5,
                weight: 6.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/petilil.png",
                pokedex_id: 548,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Lilligant",
                description: "Graceful and elegant, its fragrance is beloved worldwide.",
                height: 1.1,
                weight: 16.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/lilligant.png",
                pokedex_id: 549,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Basculin",
                description: "Red and Blue-Striped forms are constantly fighting each other.",
                height: 1.0,
                weight: 18.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/basculin.png",
                pokedex_id: 550,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Sandile",
                description: "It moves through sand as though swimming, leaving only its eyes exposed.",
                height: 0.7,
                weight: 15.2,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/sandile.png",
                pokedex_id: 551,
                type1: 15,
                type2: 8,
                generation: 5
            },
            {
                name: "Krokorok",
                description: "Still in its adolescence, it moves in groups to survive harsh deserts.",
                height: 1.0,
                weight: 33.4,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/krokorok.png",
                pokedex_id: 552,
                type1: 15,
                type2: 8,
                generation: 5
            },
            {
                name: "Krookodile",
                description: "Very violent Pokémon that can crush a car with its jaws.",
                height: 1.5,
                weight: 96.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/krookodile.png",
                pokedex_id: 553,
                type1: 15,
                type2: 8,
                generation: 5
            },
            {
                name: "Darumaka",
                description: "When it sleeps, it becomes a stone-like lump to conserve heat.",
                height: 0.6,
                weight: 37.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/darumaka.png",
                pokedex_id: 554,
                type1: 1,
                type2: null,
                generation: 5
            },
            {
                name: "Darmanitan",
                description: "Its internal fire burns at 2,500°C, making its punches devastating.",
                height: 1.3,
                weight: 92.9,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/darmanitan.png",
                pokedex_id: 555,
                type1: 1,
                type2: null,
                generation: 5
            },
            {
                name: "Maractus",
                description: "It moves rhythmically to make its seeds rattle like instruments.",
                height: 1.0,
                weight: 28.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/maractus.png",
                pokedex_id: 556,
                type1: 3,
                type2: null,
                generation: 5
            },
            {
                name: "Dwebble",
                description: "It makes its home in stones it finds. If the stone breaks, it looks for a new one.",
                height: 0.3,
                weight: 14.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/dwebble.png",
                pokedex_id: 557,
                type1: 11,
                type2: 12,
                generation: 5
            },
            {
                name: "Crustle",
                description: "It carries massive slabs on its back and competes with others for territory.",
                height: 1.4,
                weight: 200.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/crustle.png",
                pokedex_id: 558,
                type1: 11,
                type2: 12,
                generation: 5
            },
            {
                name: "Scraggy",
                description: "Its skin falls off easily. It pulls up its skin to protect itself.",
                height: 0.6,
                weight: 11.8,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/scraggy.png",
                pokedex_id: 559,
                type1: 15,
                type2: 6,
                generation: 5
            },
            {
                name: "Scrafty",
                description: "It kicks opponents with brute force and is very protective of its turf.",
                height: 1.1,
                weight: 30.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/scrafty.png",
                pokedex_id: 560,
                type1: 15,
                type2: 6,
                generation: 5
            },
            {
                name: "Sigilyph",
                description: "It flies constantly on a set route, as if protecting something.",
                height: 1.4,
                weight: 14.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/sigilyph.png",
                pokedex_id: 561,
                type1: 10,
                type2: 9,
                generation: 5
            },
            {
                name: "Yamask",
                description: "It carries a mask that used to be its human face. Staring at it makes it cry.",
                height: 0.5,
                weight: 1.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/yamask.png",
                pokedex_id: 562,
                type1: 13,
                type2: null,
                generation: 5
            },
            {
                name: "Cofagrigus",
                description: "It swallows those who get too close and turns them into mummies.",
                height: 1.7,
                weight: 76.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/cofagrigus.png",
                pokedex_id: 563,
                type1: 13,
                type2: null,
                generation: 5
            },
            {
                name: "Tirtouga",
                description: "It lived 100 million years ago. It dives deep in search of prey.",
                height: 0.7,
                weight: 16.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/tirtouga.png",
                pokedex_id: 564,
                type1: 2,
                type2: 12,
                generation: 5
            },
            {
                name: "Carracosta",
                description: "Its jaws are so strong it can bite through steel frames.",
                height: 1.2,
                weight: 81.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/carracosta.png",
                pokedex_id: 565,
                type1: 2,
                type2: 12,
                generation: 5
            },
            {
                name: "Archen",
                description: "Said to be the ancestor of all bird Pokémon. It cannot fly yet.",
                height: 0.5,
                weight: 9.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/archen.png",
                pokedex_id: 566,
                type1: 12,
                type2: 9,
                generation: 5
            },
            {
                name: "Archeops",
                description: "It is intelligent and can fly very well despite its ancient origin.",
                height: 1.4,
                weight: 32.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/archeops.png",
                pokedex_id: 567,
                type1: 12,
                type2: 9,
                generation: 5
            },
            {
                name: "Trubbish",
                description: "Formed by garbage fused with toxic chemicals. It smells awful.",
                height: 0.6,
                weight: 31.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/trubbish.png",
                pokedex_id: 568,
                type1: 7,
                type2: null,
                generation: 5
            },
            {
                name: "Garbodor",
                description: "It attacks by spraying toxic gas and corrupted sludge.",
                height: 1.9,
                weight: 107.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/garbodor.png",
                pokedex_id: 569,
                type1: 7,
                type2: null,
                generation: 5
            },
            {
                name: "Zorua",
                description: "It disguises itself as others to protect itself.",
                height: 0.7,
                weight: 12.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/zorua.png",
                pokedex_id: 570,
                type1: 15,
                type2: null,
                generation: 5
            },
            {
                name: "Zoroark",
                description: "Creates complex illusions to trick its opponents.",
                height: 1.6,
                weight: 81.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/zoroark.png",
                pokedex_id: 571,
                type1: 15,
                type2: null,
                generation: 5
            },
            {
                name: "Minccino",
                description: "They greet each other by rubbing their tails together.",
                height: 0.4,
                weight: 5.8,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/minccino.png",
                pokedex_id: 572,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Cinccino",
                description: "Its fur is coated in a special oil that repels dust and dirt.",
                height: 0.5,
                weight: 7.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/cinccino.png",
                pokedex_id: 573,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Gothita",
                description: "It stares intently at everything. This behavior makes people uncomfortable.",
                height: 0.4,
                weight: 5.8,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/gothita.png",
                pokedex_id: 574,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Gothorita",
                description: "It uses hypnosis to control others and make them do its bidding.",
                height: 0.7,
                weight: 18.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/gothorita.png",
                pokedex_id: 575,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Gothitelle",
                description: "It can predict the future based on the stars and cosmic movement.",
                height: 1.5,
                weight: 44.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/gothitelle.png",
                pokedex_id: 576,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Solosis",
                description: "They communicate by using telepathy from within their gel bodies.",
                height: 0.3,
                weight: 1.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/solosis.png",
                pokedex_id: 577,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Duosion",
                description: "Because the two halves of its brain don’t always work together, it can be clumsy.",
                height: 0.6,
                weight: 8.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/duosion.png",
                pokedex_id: 578,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Reuniclus",
                description: "Using psychic power, it can lift enormous boulders with ease.",
                height: 1.0,
                weight: 20.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/reuniclus.png",
                pokedex_id: 579,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Ducklett",
                description: "They are better at swimming than flying, and they happily play in rivers.",
                height: 0.5,
                weight: 5.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/ducklett.png",
                pokedex_id: 580,
                type1: 2,
                type2: 9,
                generation: 5
            },
            {
                name: "Swanna",
                description: "Swanna start to dance at dusk. The one dancing in the middle is the leader of the flock.",
                height: 1.3,
                weight: 24.2,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/swanna.png",
                pokedex_id: 581,
                type1: 2,
                type2: 9,
                generation: 5
            },
            {
                name: "Vanillite",
                description: "Snow crystals form naturally on this Pokémon's body as it walks.",
                height: 0.4,
                weight: 5.7,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/vanillite.png",
                pokedex_id: 582,
                type1: 5,
                type2: null,
                generation: 5
            },
            {
                name: "Vanillish",
                description: "It blasts enemies with cold air reaching -148°F, freezing them solid.",
                height: 1.1,
                weight: 41.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/vanillish.png",
                pokedex_id: 583,
                type1: 5,
                type2: null,
                generation: 5
            },
            {
                name: "Vanilluxe",
                description: "If both of its heads get angry simultaneously, it expels a blizzard, burying everything in snow.",
                height: 1.3,
                weight: 57.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/vanilluxe.png",
                pokedex_id: 584,
                type1: 5,
                type2: null,
                generation: 5
            },
            {
                name: "Deerling",
                description: "The color and scent of its fur change with the seasons.",
                height: 0.6,
                weight: 19.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/deerling.png",
                pokedex_id: 585,
                type1: 18,
                type2: 3,
                generation: 5
            },
            {
                name: "Sawsbuck",
                description: "The plants growing on its horns change with the seasons, giving it an elegant appearance.",
                height: 1.9,
                weight: 92.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/sawsbuck.png",
                pokedex_id: 586,
                type1: 18,
                type2: 3,
                generation: 5
            },
            {
                name: "Emolga",
                description: "They live on treetops and glide using their cape-like membranes.",
                height: 0.4,
                weight: 5.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/emolga.png",
                pokedex_id: 587,
                type1: 4,
                type2: 9,
                generation: 5
            },
            {
                name: "Karrablast",
                description: "When it sees a Shelmet, it gets excited and attacks.",
                height: 0.5,
                weight: 5.9,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/karrablast.png",
                pokedex_id: 588,
                type1: 11,
                type2: null,
                generation: 5
            },
            {
                name: "Escavalier",
                description: "They fly around at high speed, attacking enemies with lances.",
                height: 1.0,
                weight: 33.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/escavalier.png",
                pokedex_id: 589,
                type1: 11,
                type2: 16,
                generation: 5
            },
            {
                name: "Foongus",
                description: "It lures Pokémon in with its Poké Ball-like pattern, then releases spores.",
                height: 0.2,
                weight: 1.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/foongus.png",
                pokedex_id: 590,
                type1: 3,
                type2: 7,
                generation: 5
            },
            {
                name: "Amoonguss",
                description: "It uses its Poké Ball-like patterns to bait prey.",
                height: 0.6,
                weight: 10.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/amoonguss.png",
                pokedex_id: 591,
                type1: 3,
                type2: 7,
                generation: 5
            },
            {
                name: "Frillish",
                description: "Its body is filled with seawater, and anyone who touches it will be wrapped in its veil of poison.",
                height: 1.2,
                weight: 33.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/frillish.png",
                pokedex_id: 592,
                type1: 2,
                type2: 13,
                generation: 5
            },
            {
                name: "Jellicent",
                description: "The fate of those who encounter it in the open sea is said to be sealed.",
                height: 2.2,
                weight: 135.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/jellicent.png",
                pokedex_id: 593,
                type1: 2,
                type2: 13,
                generation: 5
            },
            {
                name: "Alomomola",
                description: "It heals injuries of Pokémon by wrapping them with its special membrane.",
                height: 1.2,
                weight: 31.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/alomomola.png",
                pokedex_id: 594,
                type1: 2,
                type2: null,
                generation: 5
            },
            {
                name: "Joltik",
                description: "It attaches itself to larger Pokémon and absorbs static electricity.",
                height: 0.1,
                weight: 0.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/joltik.png",
                pokedex_id: 595,
                type1: 11,
                type2: 4,
                generation: 5
            },
            {
                name: "Galvantula",
                description: "It lays electrified threads to trap its enemies.",
                height: 0.8,
                weight: 14.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/galvantula.png",
                pokedex_id: 596,
                type1: 11,
                type2: 4,
                generation: 5
            },
            {
                name: "Ferroseed",
                description: "It absorbs minerals from the walls of caves.",
                height: 0.6,
                weight: 18.8,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/ferroseed.png",
                pokedex_id: 597,
                type1: 3,
                type2: 16,
                generation: 5
            },
            {
                name: "Ferrothorn",
                description: "It swings its spikes and vines wildly to attack.",
                height: 1.0,
                weight: 110.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/ferrothorn.png",
                pokedex_id: 598,
                type1: 3,
                type2: 16,
                generation: 5
            },
            {
                name: "Klink",
                description: "The two bodies spin around each other to generate energy.",
                height: 0.3,
                weight: 21.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/klink.png",
                pokedex_id: 599,
                type1: 16,
                type2: null,
                generation: 5
            },
            {
                name: "Klang",
                description: "By changing the direction it spins, it communicates its feelings to others.",
                height: 0.6,
                weight: 51.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/klang.png",
                pokedex_id: 600,
                type1: 16,
                type2: null,
                generation: 5
            },
            {
                name: "Klinklang",
                description: "Its red core spins at high speed to generate powerful energy.",
                height: 0.6,
                weight: 81.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/klinklang.png",
                pokedex_id: 601,
                type1: 16,
                type2: null,
                generation: 5
            },
            {
                name: "Tynamo",
                description: "One alone doesn't have much power, so they gather in groups.",
                height: 0.2,
                weight: 0.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/tynamo.png",
                pokedex_id: 602,
                type1: 4,
                type2: null,
                generation: 5
            },
            {
                name: "Eelektrik",
                description: "It wraps itself around its prey and shocks them with electricity.",
                height: 1.2,
                weight: 22.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/eelektrik.png",
                pokedex_id: 603,
                type1: 4,
                type2: null,
                generation: 5
            },
            {
                name: "Eelektross",
                description: "It drags prey into the ocean depths with its sucker mouth.",
                height: 2.1,
                weight: 80.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/eelektross.png",
                pokedex_id: 604,
                type1: 4,
                type2: null,
                generation: 5
            },
            {
                name: "Elgyem",
                description: "It uses psychic power to control others’ minds.",
                height: 0.5,
                weight: 9.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/elgyem.png",
                pokedex_id: 605,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Beheeyem",
                description: "It communicates by flashing its fingers in patterns.",
                height: 1.0,
                weight: 34.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/beheeyem.png",
                pokedex_id: 606,
                type1: 10,
                type2: null,
                generation: 5
            },
            {
                name: "Litwick",
                description: "Its flame is powered by the life energy it absorbs from people and Pokémon.",
                height: 0.3,
                weight: 3.1,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/litwick.png",
                pokedex_id: 607,
                type1: 1,
                type2: 13,
                generation: 5
            },
            {
                name: "Lampent",
                description: "It arrives near the moment of death and steals the spirit from the body.",
                height: 0.6,
                weight: 13.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/lampent.png",
                pokedex_id: 608,
                type1: 1,
                type2: 13,
                generation: 5
            },
            {
                name: "Chandelure",
                description: "Its flames burn the spirit, leaving the body behind.",
                height: 1.0,
                weight: 34.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/chandelure.png",
                pokedex_id: 609,
                type1: 1,
                type2: 13,
                generation: 5
            },
            {
                name: "Axew",
                description: "They mark their territory by leaving gashes in trees. These deep gashes can stay for years.",
                height: 0.6,
                weight: 18.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/axew.png",
                pokedex_id: 610,
                type1: 14,
                type2: null,
                generation: 5
            },
            {
                name: "Fraxure",
                description: "Their tusks are strong and sharp. They can cut through thick trees in a single strike.",
                height: 1.0,
                weight: 36.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/fraxure.png",
                pokedex_id: 611,
                type1: 14,
                type2: null,
                generation: 5
            },
            {
                name: "Haxorus",
                description: "Their sturdy tusks will never break, even if used to cut steel beams.",
                height: 1.8,
                weight: 105.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/haxorus.png",
                pokedex_id: 612,
                type1: 14,
                type2: null,
                generation: 5
            },
            {
                name: "Cubchoo",
                description: "It wipes its nose and spreads its icy mucus, which has powerful freezing properties.",
                height: 0.5,
                weight: 8.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/cubchoo.png",
                pokedex_id: 613,
                type1: 5,
                type2: null,
                generation: 5
            },
            {
                name: "Beartic",
                description: "It freezes its breath to create cold air blades to attack.",
                height: 2.6,
                weight: 260.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/beartic.png",
                pokedex_id: 614,
                type1: 5,
                type2: null,
                generation: 5
            },
            {
                name: "Cryogonal",
                description: "They are born in snow clouds. They use ice chains to capture prey.",
                height: 1.1,
                weight: 148.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/cryogonal.png",
                pokedex_id: 615,
                type1: 5,
                type2: null,
                generation: 5
            },
            {
                name: "Shelmet",
                description: "It evolves when bathed in the energy released from Karrablast's evolution.",
                height: 0.4,
                weight: 7.7,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/shelmet.png",
                pokedex_id: 616,
                type1: 11,
                type2: null,
                generation: 5
            },
            {
                name: "Accelgor",
                description: "Having removed its shell, it moves at blinding speed.",
                height: 0.8,
                weight: 25.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/accelgor.png",
                pokedex_id: 617,
                type1: 11,
                type2: null,
                generation: 5
            },
            {
                name: "Stunfisk",
                description: "Its skin generates electricity. It smiles while waiting for prey.",
                height: 0.7,
                weight: 11.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/stunfisk.png",
                pokedex_id: 618,
                type1: 8,
                type2: 4,
                generation: 5
            },
            {
                name: "Mienfoo",
                description: "They tirelessly practice their martial arts, becoming sharper with every move.",
                height: 0.9,
                weight: 20.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/mienfoo.png",
                pokedex_id: 619,
                type1: 6,
                type2: null,
                generation: 5
            },
            {
                name: "Mienshao",
                description: "It wields its long arm fur like whips to unleash powerful strikes.",
                height: 1.4,
                weight: 35.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/mienshao.png",
                pokedex_id: 620,
                type1: 6,
                type2: null,
                generation: 5
            },
            {
                name: "Druddigon",
                description: "It lives in caves and absorbs sunlight to warm its body.",
                height: 1.6,
                weight: 139.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/druddigon.png",
                pokedex_id: 621,
                type1: 14,
                type2: null,
                generation: 5
            },
            {
                name: "Golett",
                description: "Ancient science fashioned this Pokémon from clay. It moves thanks to a mysterious energy.",
                height: 1.0,
                weight: 92.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/golett.png",
                pokedex_id: 622,
                type1: 13,
                type2: 8,
                generation: 5
            },
            {
                name: "Golurk",
                description: "Its internal energy runs wild if the seal on its chest is removed.",
                height: 2.8,
                weight: 330.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/golurk.png",
                pokedex_id: 623,
                type1: 13,
                type2: 8,
                generation: 5
            },
            {
                name: "Pawniard",
                description: "Ignoring injury, it attacks by slashing with its bladed body.",
                height: 0.5,
                weight: 10.2,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/pawniard.png",
                pokedex_id: 624,
                type1: 15,
                type2: 16,
                generation: 5
            },
            {
                name: "Bisharp",
                description: "It leads a group of Pawniard. Any member that disobeys is punished.",
                height: 1.6,
                weight: 70.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/bisharp.png",
                pokedex_id: 625,
                type1: 15,
                type2: 16,
                generation: 5
            },
            {
                name: "Bouffalant",
                description: "Their fluffy fur absorbs damage. They headbutt anything that enters their territory.",
                height: 1.6,
                weight: 94.6,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/bouffalant.png",
                pokedex_id: 626,
                type1: 18,
                type2: null,
                generation: 5
            },
            {
                name: "Rufflet",
                description: "It stands up to massive opponents, not backing down even if it gets hurt.",
                height: 0.5,
                weight: 10.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/rufflet.png",
                pokedex_id: 627,
                type1: 18,
                type2: 9,
                generation: 5
            },
            {
                name: "Braviary",
                description: "The more scars it has, the more respect it gets from its peers.",
                height: 1.5,
                weight: 41.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/braviary.png",
                pokedex_id: 628,
                type1: 18,
                type2: 9,
                generation: 5
            },
            {
                name: "Vullaby",
                description: "Its bones become harder as it grows. It protects itself with the skull-like diaper.",
                height: 0.5,
                weight: 9.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/vullaby.png",
                pokedex_id: 629,
                type1: 15,
                type2: 9,
                generation: 5
            },
            {
                name: "Mandibuzz",
                description: "It circles in the sky, keeping a keen eye out for weak Pokémon to pick off.",
                height: 1.2,
                weight: 39.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/mandibuzz.png",
                pokedex_id: 630,
                type1: 15,
                type2: 9,
                generation: 5
            },
            {
                name: "Heatmor",
                description: "It burns through Durant’s steel bodies with its tongue of fire.",
                height: 1.4,
                weight: 58.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/heatmor.png",
                pokedex_id: 631,
                type1: 1,
                type2: null,
                generation: 5
            },
            {
                name: "Durant",
                description: "They attack in swarms, biting and tearing at foes with their steel jaws.",
                height: 0.3,
                weight: 33.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/durant.png",
                pokedex_id: 632,
                type1: 11,
                type2: 16,
                generation: 5
            },
            {
                name: "Deino",
                description: "It bites anything that moves because it can't see. Its body is tough and resilient.",
                height: 0.8,
                weight: 17.3,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/deino.png",
                pokedex_id: 633,
                type1: 15,
                type2: 14,
                generation: 5
            },
            {
                name: "Zweilous",
                description: "The two heads constantly fight over food, causing it to go on rampages.",
                height: 1.4,
                weight: 50.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/zweilous.png",
                pokedex_id: 634,
                type1: 15,
                type2: 14,
                generation: 5
            },
            {
                name: "Hydreigon",
                description: "The three heads take down anything that moves. It is a devastatingly powerful Pokémon.",
                height: 1.8,
                weight: 160.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/hydreigon.png",
                pokedex_id: 635,
                type1: 15,
                type2: 14,
                generation: 5
            },
            {
                name: "Larvesta",
                description: "The flames on its body are a defense mechanism. It lives in volcanoes.",
                height: 1.1,
                weight: 28.8,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/larvesta.png",
                pokedex_id: 636,
                type1: 1,
                type2: 11,
                generation: 5
            },
            {
                name: "Volcarona",
                description: "It scatters burning scales that can replace the sun when volcanic ash blocks out the sky.",
                height: 1.6,
                weight: 46.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/volcarona.png",
                pokedex_id: 637,
                type1: 1,
                type2: 11,
                generation: 5
            },
            {
                name: "Cobalion",
                description: "It has a calm and composed demeanor. Its glare can halt even an unruly Pokémon.",
                height: 2.1,
                weight: 250.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/cobalion.png",
                pokedex_id: 638,
                type1: 16,
                type2: 6,
                generation: 5
            },
            {
                name: "Terrakion",
                description: "Its charge can destroy a sturdy castle wall. It battles to protect its allies.",
                height: 1.9,
                weight: 260.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/terrakion.png",
                pokedex_id: 639,
                type1: 12,
                type2: 6,
                generation: 5
            },
            {
                name: "Virizion",
                description: "Its movements are elegant and swift. It fights to protect Pokémon from humans.",
                height: 2.0,
                weight: 200.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/virizion.png",
                pokedex_id: 640,
                type1: 3,
                type2: 6,
                generation: 5
            },
            {
                name: "Tornadus",
                description: "It rides the wind and causes storms as it flies. Its power can blow away houses.",
                height: 1.5,
                weight: 63.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/tornadus.png",
                pokedex_id: 641,
                type1: 9,
                type2: null,
                generation: 5
            },
            {
                name: "Thundurus",
                description: "It flies around striking the ground with lightning, causing forest fires.",
                height: 1.5,
                weight: 61.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/thundurus.png",
                pokedex_id: 642,
                type1: 4,
                type2: 9,
                generation: 5
            },
            {
                name: "Reshiram",
                description: "Its flames heat the atmosphere and can incinerate everything around it.",
                height: 3.2,
                weight: 330.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/reshiram.png",
                pokedex_id: 643,
                type1: 1,
                type2: 14,
                generation: 5
            },
            {
                name: "Zekrom",
                description: "It generates powerful electricity and can power an entire city.",
                height: 2.9,
                weight: 345.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/zekrom.png",
                pokedex_id: 644,
                type1: 4,
                type2: 14,
                generation: 5
            },
            {
                name: "Landorus",
                description: "The energy it creates from the land’s nutrients helps crops grow.",
                height: 1.5,
                weight: 68.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/landorus.png",
                pokedex_id: 645,
                type1: 8,
                type2: 9,
                generation: 5
            },
            {
                name: "Kyurem",
                description: "It is said to be the empty shell left over when Reshiram and Zekrom split.",
                height: 3.0,
                weight: 325.0,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/kyurem.png",
                pokedex_id: 646,
                type1: 5,
                type2: 14,
                generation: 5
            },
            {
                name: "Keldeo",
                description: "It crosses the world running across the water’s surface. It trains to master sword-like horns.",
                height: 1.4,
                weight: 48.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/keldeo.png",
                pokedex_id: 647,
                type1: 2,
                type2: 6,
                generation: 5
            },
            {
                name: "Meloetta",
                description: "Its melodies have the power to make Pokémon feel happiness and sadness.",
                height: 0.6,
                weight: 6.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/meloetta.png",
                pokedex_id: 648,
                type1: 10,
                type2: 18,
                generation: 5
            },
            {
                name: "Genesect",
                description: "An ancient bug Pokémon revived and upgraded by Team Plasma. It fires blasts from its cannon.",
                height: 1.5,
                weight: 82.5,
                region_id: 5,
                image: "http://localhost:3000/uploads/pokemon/genesect.png",
                pokedex_id: 649,
                type1: 11,
                type2: 16,
                generation: 5
            }

        ]

        for (let pokemon of poke) {
            await pool.query(`
                INSERT INTO pokemon (name, description, height, weight, region_id, image, pokedex_id, type1, type2, generation) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT (name) DO NOTHING`,
                [pokemon.name, pokemon.description, pokemon.height, pokemon.weight, pokemon.region_id, pokemon.image, pokemon.pokedex_id, pokemon.type1, pokemon.type2, pokemon.generation])
        }

        console.log("Berhasil Membuat Pokemon Gen 5")
    }
    catch (err) {
        console.log("Gagal Membuat Pokemon Gen 5")
    }
}

module.exports = pokemonGen5Seeder