const pool = require("../../db")

async function pokemonGen4Seeder() {
    try {
        const poke = [
            {
                name: "Turtwig",
                description: "It stores energy in its body and grows stronger by photosynthesis.",
                height: 0.4,
                weight: 10.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/turtwig.png",
                pokedex_id: 387,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Grotle",
                description: "Its sturdy legs support a shell full of soil. It feeds on sunlight.",
                height: 1.1,
                weight: 97.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/grotle.png",
                pokedex_id: 388,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Torterra",
                description: "It carries a small forest on its back and is extremely strong.",
                height: 2.2,
                weight: 310.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/torterra.png",
                pokedex_id: 389,
                type1: 3,
                type2: 8,
                generation: 4
            },
            {
                name: "Chimchar",
                description: "Its tail flame indicates its life force. It loves to play.",
                height: 0.5,
                weight: 6.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/chimchar.png",
                pokedex_id: 390,
                type1: 1,
                type2: null,
                generation: 4
            },
            {
                name: "Monferno",
                description: "It is agile and can fight while jumping on opponents.",
                height: 0.9,
                weight: 22.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/monferno.png",
                pokedex_id: 391,
                type1: 1,
                type2: 6,
                generation: 4
            },
            {
                name: "Infernape",
                description: "It is extremely fast and wields its fiery fists skillfully in battle.",
                height: 1.2,
                weight: 55.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/infernape.png",
                pokedex_id: 392,
                type1: 1,
                type2: 6,
                generation: 4
            },
            {
                name: "Piplup",
                description: "It is very proud. It does not run from battles and refuses help.",
                height: 0.4,
                weight: 5.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/piplup.png",
                pokedex_id: 393,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Prinplup",
                description: "It is dignified and often trains itself rigorously for battle.",
                height: 0.8,
                weight: 23.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/prinplup.png",
                pokedex_id: 394,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Empoleon",
                description: "It has a steel-like chest that can slice through iron, giving it great offense.",
                height: 1.7,
                weight: 84.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/empoleon.png",
                pokedex_id: 395,
                type1: 2,
                type2: 16,
                generation: 4
            },
            {
                name: "Starly",
                description: "It is common in Sinnoh and forms large flocks for protection.",
                height: 0.3,
                weight: 2.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/starly.png",
                pokedex_id: 396,
                type1: 18,
                type2: 9,
                generation: 4
            },
            {
                name: "Staravia",
                description: "It grows stronger in flocks and has a strong sense of direction.",
                height: 0.6,
                weight: 15.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/staravia.png",
                pokedex_id: 397,
                type1: 18,
                type2: 9,
                generation: 4
            },
            {
                name: "Staraptor",
                description: "It is extremely powerful and aggressive. It leads flocks with authority.",
                height: 1.2,
                weight: 24.9,
                region_id: 4,
                image: "http://localhost:3000/uploads/staraptor.png",
                pokedex_id: 398,
                type1: 18,
                type2: 9,
                generation: 4
            },
            {
                name: "Bidoof",
                description: "It is clumsy but hardworking and builds dams in rivers.",
                height: 0.5,
                weight: 20.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/bidoof.png",
                pokedex_id: 399,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Bibarel",
                description: "It is strong and a capable swimmer, building dams and nests.",
                height: 1.0,
                weight: 31.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/bibarel.png",
                pokedex_id: 400,
                type1: 18,
                type2: 8,
                generation: 4
            },
            {
                name: "Kricketot",
                description: "It communicates with others by chirping rhythmically.",
                height: 0.3,
                weight: 2.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/kricketot.png",
                pokedex_id: 401,
                type1: 11,
                type2: null,
                generation: 4
            },
            {
                name: "Kricketune",
                description: "It signals its emotions and territory through complex chirps.",
                height: 1.0,
                weight: 25.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/kricketune.png",
                pokedex_id: 402,
                type1: 11,
                type2: null,
                generation: 4
            },
            {
                name: "Shinx",
                description: "It stores electricity in its body and generates sparks.",
                height: 0.5,
                weight: 9.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/shinx.png",
                pokedex_id: 403,
                type1: 4,
                type2: null,
                generation: 4
            },
            {
                name: "Luxio",
                description: "Its fangs crackle with electricity. It is very brave.",
                height: 0.9,
                weight: 30.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/luxio.png",
                pokedex_id: 404,
                type1: 4,
                type2: null,
                generation: 4
            },
            {
                name: "Luxray",
                description: "It can see through objects using its eyes that detect electromagnetic waves.",
                height: 1.4,
                weight: 42.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/luxray.png",
                pokedex_id: 405,
                type1: 4,
                type2: null,
                generation: 4
            },
            {
                name: "Budew",
                description: "It grows by absorbing nutrients and thrives in shady areas.",
                height: 0.2,
                weight: 1.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/budew.png",
                pokedex_id: 406,
                type1: 3,
                type2: 7,
                generation: 4
            },
            {
                name: "Roserade",
                description: "It creates bouquets of poisonous flowers to defend itself.",
                height: 0.9,
                weight: 14.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/roserade.png",
                pokedex_id: 407,
                type1: 3,
                type2: 7,
                generation: 4
            },
            {
                name: "Cranidos",
                description: "It uses its hard head to ram opponents.",
                height: 0.9,
                weight: 31.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/cranidos.png",
                pokedex_id: 408,
                type1: 11,
                type2: null,
                generation: 4
            },
            {
                name: "Rampardos",
                description: "Its skull is extremely hard and can crush boulders.",
                height: 1.6,
                weight: 102.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/rampardos.png",
                pokedex_id: 409,
                type1: 11,
                type2: null,
                generation: 4
            },
            {
                name: "Shieldon",
                description: "It uses its shield-like head to protect itself from predators.",
                height: 0.5,
                weight: 57.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/shieldon.png",
                pokedex_id: 410,
                type1: 12,
                type2: 16,
                generation: 4
            },
            {
                name: "Bastiodon",
                description: "It stands still for hours and uses its strong faceplate for defense.",
                height: 1.3,
                weight: 149.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/bastiodon.png",
                pokedex_id: 411,
                type1: 12,
                type2: 16,
                generation: 4
            },
            {
                name: "Burmy",
                description: "It wears cloaks made from plants to adapt to its surroundings.",
                height: 0.2,
                weight: 3.4,
                region_id: 4,
                image: "http://localhost:3000/uploads/burmy.png",
                pokedex_id: 412,
                type1: 11,
                type2: null,
                generation: 4
            },
            {
                name: "Wormadam",
                description: "It evolves from Burmy and wears cloaks of different materials based on location.",
                height: 0.5,
                weight: 6.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/wormadam.png",
                pokedex_id: 413,
                type1: 11,
                type2: 3,
                generation: 4
            },
            {
                name: "Mothim",
                description: "It evolves from a male Burmy and spreads pollen while flying.",
                height: 0.9,
                weight: 23.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/mothim.png",
                pokedex_id: 414,
                type1: 11,
                type2: 9,
                generation: 4
            },
            {
                name: "Combee",
                description: "It lives in colonies and gathers nectar diligently.",
                height: 0.3,
                weight: 5.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/combee.png",
                pokedex_id: 415,
                type1: 11,
                type2: 4,
                generation: 4
            },
            {
                name: "Vespiquen",
                description: "It rules over Combee colonies and protects them fiercely.",
                height: 1.2,
                weight: 38.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/vespiquen.png",
                pokedex_id: 416,
                type1: 11,
                type2: 4,
                generation: 4
            },
            {
                name: "Pachirisu",
                description: "It stores electricity in its cheeks to shock attackers.",
                height: 0.4,
                weight: 3.9,
                region_id: 4,
                image: "http://localhost:3000/uploads/pachirisu.png",
                pokedex_id: 417,
                type1: 4,
                type2: null,
                generation: 4
            },
            {
                name: "Buizel",
                description: "It swims skillfully using its tail fins as rudders.",
                height: 0.7,
                weight: 29.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/buizel.png",
                pokedex_id: 418,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Floatzel",
                description: "Its body is coated with oil to make it float and swim fast.",
                height: 1.1,
                weight: 33.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/floatzel.png",
                pokedex_id: 419,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Cherubi",
                description: "It stores energy in its red ball to power its evolution.",
                height: 0.4,
                weight: 3.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/cherubi.png",
                pokedex_id: 420,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Cherrim",
                description: "It opens its petals under the sun and shares sunlight energy with others.",
                height: 0.5,
                weight: 9.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/cherrim.png",
                pokedex_id: 421,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Shellos",
                description: "It lives on the seafloor and absorbs nutrients from sand and water.",
                height: 0.3,
                weight: 6.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/shellos.png",
                pokedex_id: 422,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Gastrodon",
                description: "It evolves from Shellos and has a soft, flexible body for survival.",
                height: 0.9,
                weight: 29.9,
                region_id: 4,
                image: "http://localhost:3000/uploads/gastrodon.png",
                pokedex_id: 423,
                type1: 2,
                type2: 8,
                generation: 4
            },
            {
                name: "Ambipom",
                description: "Its tail ends split into two hands, giving it remarkable dexterity.",
                height: 1.2,
                weight: 20.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/ambipom.png",
                pokedex_id: 424,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Drifloon",
                description: "It is a balloon Pokémon that drifts along the wind, sometimes carrying people away.",
                height: 0.4,
                weight: 1.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/drifloon.png",
                pokedex_id: 425,
                type1: 13,
                type2: 9,
                generation: 4
            },
            {
                name: "Drifblim",
                description: "It is heavier than it looks and can carry large loads by floating.",
                height: 1.7,
                weight: 15.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/drifblim.png",
                pokedex_id: 426,
                type1: 13,
                type2: 9,
                generation: 4
            },
            {
                name: "Buneary",
                description: "It hops energetically and is adored for its cute appearance.",
                height: 0.4,
                weight: 5.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/buneary.png",
                pokedex_id: 427,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Lopunny",
                description: "Its legs are extremely strong, allowing it to dodge attacks skillfully.",
                height: 1.2,
                weight: 33.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/lopunny.png",
                pokedex_id: 428,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Mismagius",
                description: "It casts curses and produces mysterious sounds that confuse opponents.",
                height: 0.9,
                weight: 4.4,
                region_id: 4,
                image: "http://localhost:3000/uploads/mismagius.png",
                pokedex_id: 429,
                type1: 13,
                type2: null,
                generation: 4
            },
            {
                name: "Honchkrow",
                description: "It leads Murkrow flocks and is considered a mysterious Pokémon.",
                height: 0.9,
                weight: 27.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/honchkrow.png",
                pokedex_id: 430,
                type1: 15,
                type2: 9,
                generation: 4
            },
            {
                name: "Glameow",
                description: "It is haughty and dislikes dirty places. It scratches those who annoy it.",
                height: 0.5,
                weight: 3.9,
                region_id: 4,
                image: "http://localhost:3000/uploads/glameow.png",
                pokedex_id: 431,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Purugly",
                description: "It is strong and aggressive despite its bulky and clumsy appearance.",
                height: 1.0,
                weight: 43.8,
                region_id: 4,
                image: "http://localhost:3000/uploads/purugly.png",
                pokedex_id: 432,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Chingling",
                description: "It communicates by ringing its bell-shaped body, summoning other Chingling.",
                height: 0.2,
                weight: 0.6,
                region_id: 4,
                image: "http://localhost:3000/uploads/chingling.png",
                pokedex_id: 433,
                type1: 10,
                type2: null,
                generation: 4
            },
            {
                name: "Stunky",
                description: "It sprays a foul-smelling liquid to repel attackers.",
                height: 0.4,
                weight: 19.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/stunky.png",
                pokedex_id: 434,
                type1: 7,
                type2: 15,
                generation: 4
            },
            {
                name: "Skuntank",
                description: "It has strong scent glands that spray poison gas to protect itself.",
                height: 1.0,
                weight: 38.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/skuntank.png",
                pokedex_id: 435,
                type1: 7,
                type2: 15,
                generation: 4
            },
            {
                name: "Bronzor",
                description: "Its body is made of iron. It uses psychic power to detect threats.",
                height: 0.5,
                weight: 60.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/bronzor.png",
                pokedex_id: 436,
                type1: 16,
                type2: 10,
                generation: 4
            },
            {
                name: "Bronzong",
                description: "It is said to bring rain when it appears. Its body is incredibly heavy.",
                height: 1.3,
                weight: 187.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/bronzong.png",
                pokedex_id: 437,
                type1: 16,
                type2: 10,
                generation: 4
            },
            {
                name: "Bonsly",
                description: "It mimics rocks to avoid predators but cries if ignored.",
                height: 0.5,
                weight: 15.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/bonsly.png",
                pokedex_id: 438,
                type1: 12,
                type2: null,
                generation: 4
            },
            {
                name: "Mime Jr.",
                description: "It practices psychic powers and mimics adults to learn skills.",
                height: 0.6,
                weight: 13.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/mimejr.png",
                pokedex_id: 439,
                type1: 10,
                type2: 18,
                generation: 4
            },
            {
                name: "Happiny",
                description: "It carries an egg and is very happy when interacting with others.",
                height: 0.6,
                weight: 24.4,
                region_id: 4,
                image: "http://localhost:3000/uploads/happiny.png",
                pokedex_id: 440,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Chatot",
                description: "It can mimic human speech and other sounds.",
                height: 0.5,
                weight: 1.9,
                region_id: 4,
                image: "http://localhost:3000/uploads/chatot.png",
                pokedex_id: 441,
                type1: 18,
                type2: 9,
                generation: 4
            },
            {
                name: "Spiritomb",
                description: "It is bound to a keystone by 108 spirits.",
                height: 1.0,
                weight: 108.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/spiritomb.png",
                pokedex_id: 442,
                type1: 13,
                type2: 15,
                generation: 4
            },
            {
                name: "Gible",
                description: "It burrows into the ground and has a voracious appetite.",
                height: 0.7,
                weight: 20.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/gible.png",
                pokedex_id: 443,
                type1: 8,
                type2: 14,
                generation: 4
            },
            {
                name: "Gabite",
                description: "It swims through sand like water and attacks with sharp claws.",
                height: 1.4,
                weight: 56.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/gabite.png",
                pokedex_id: 444,
                type1: 8,
                type2: 14,
                generation: 4
            },
            {
                name: "Garchomp",
                description: "It is fast and powerful. Its fins slice through the air and water alike.",
                height: 1.9,
                weight: 95.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/garchomp.png",
                pokedex_id: 445,
                type1: 8,
                type2: 14,
                generation: 4
            },
            {
                name: "Munchlax",
                description: "It eats constantly and stores energy for evolution.",
                height: 0.6,
                weight: 105.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/munchlax.png",
                pokedex_id: 446,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Riolu",
                description: "It can sense emotions and evolves when it bonds strongly with its trainer.",
                height: 0.7,
                weight: 20.2,
                region_id: 4,
                image: "http://localhost:3000/uploads/riolu.png",
                pokedex_id: 447,
                type1: 6,
                type2: null,
                generation: 4
            },
            {
                name: "Lucario",
                description: "It uses aura to sense opponents' movements and attacks precisely.",
                height: 1.2,
                weight: 54.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/lucario.png",
                pokedex_id: 448,
                type1: 6,
                type2: 10,
                generation: 4
            },
            {
                name: "Hippopotas",
                description: "It burrows into sand and uses its strong jaw to attack.",
                height: 0.8,
                weight: 49.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/hippopotas.png",
                pokedex_id: 449,
                type1: 8,
                type2: null,
                generation: 4
            },
            {
                name: "Hippowdon",
                description: "It creates sandstorms with its massive body to intimidate rivals.",
                height: 2.0,
                weight: 300.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/hippowdon.png",
                pokedex_id: 450,
                type1: 8,
                type2: null,
                generation: 4
            },
            {
                name: "Skorupi",
                description: "It uses pincers to catch prey and defend itself.",
                height: 0.8,
                weight: 12.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/skorupi.png",
                pokedex_id: 451,
                type1: 7,
                type2: 9,
                generation: 4
            },
            {
                name: "Drapion",
                description: "It is a predator with a poisonous tail, feared in the night.",
                height: 1.3,
                weight: 61.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/drapion.png",
                pokedex_id: 452,
                type1: 7,
                type2: 15,
                generation: 4
            },
            {
                name: "Croagunk",
                description: "It stores poison in its cheeks and attacks skillfully.",
                height: 0.7,
                weight: 23.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/croagunk.png",
                pokedex_id: 453,
                type1: 6,
                type2: 7,
                generation: 4
            },
            {
                name: "Toxicroak",
                description: "It can release poisonous spikes from its hands to strike opponents.",
                height: 1.3,
                weight: 44.4,
                region_id: 4,
                image: "http://localhost:3000/uploads/toxicroak.png",
                pokedex_id: 454,
                type1: 6,
                type2: 7,
                generation: 4
            },
            {
                name: "Carnivine",
                description: "It waits in marshes, snapping up prey with its jaw-like leaves.",
                height: 1.4,
                weight: 27.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/carnivine.png",
                pokedex_id: 455,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Finneon",
                description: "It swims gracefully and lights up dark waters with glowing fins.",
                height: 0.4,
                weight: 7.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/finneon.png",
                pokedex_id: 456,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Lumineon",
                description: "It evolves from Finneon and glides through the water elegantly.",
                height: 1.2,
                weight: 24.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/lumineon.png",
                pokedex_id: 457,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Mantyke",
                description: "It rides on larger Pokémon and uses its wings to glide above water.",
                height: 0.4,
                weight: 65.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/mantyke.png",
                pokedex_id: 458,
                type1: 2,
                type2: 9,
                generation: 4
            },
            {
                name: "Snover",
                description: "It spreads snow and ice as it grows, blending into snowy environments.",
                height: 1.0,
                weight: 50.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/snover.png",
                pokedex_id: 459,
                type1: 3,
                type2: 5,
                generation: 4
            },
            {
                name: "Abomasnow",
                description: "It grows even larger in the snow and spreads blizzards with its breath.",
                height: 2.2,
                weight: 135.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/abomasnow.png",
                pokedex_id: 460,
                type1: 3,
                type2: 5,
                generation: 4
            },
            {
                name: "Weavile",
                description: "It is quick and cunning, attacking in a coordinated fashion with its claws.",
                height: 1.1,
                weight: 34.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/weavile.png",
                pokedex_id: 461,
                type1: 15,
                type2: 5,
                generation: 4
            },
            {
                name: "Magnezone",
                description: "It evolves from Magneton and emits strong magnetic fields.",
                height: 1.2,
                weight: 180.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/magnezone.png",
                pokedex_id: 462,
                type1: 4,
                type2: 16,
                generation: 4
            },
            {
                name: "Lickilicky",
                description: "It uses its long tongue to grab and move objects.",
                height: 1.7,
                weight: 140.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/lickilicky.png",
                pokedex_id: 463,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Rhyperior",
                description: "It is extremely durable and uses its body to attack aggressively.",
                height: 2.4,
                weight: 282.8,
                region_id: 4,
                image: "http://localhost:3000/uploads/rhyperior.png",
                pokedex_id: 464,
                type1: 8,
                type2: 12,
                generation: 4
            },
            {
                name: "Tangrowth",
                description: "It traps opponents with its vines and squeezes them with enormous strength.",
                height: 2.0,
                weight: 128.6,
                region_id: 4,
                image: "http://localhost:3000/uploads/tangrowth.png",
                pokedex_id: 465,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Electivire",
                description: "It generates electricity from its tails and uses it to attack enemies.",
                height: 1.8,
                weight: 138.6,
                region_id: 4,
                image: "http://localhost:3000/uploads/electivire.png",
                pokedex_id: 466,
                type1: 4,
                type2: null,
                generation: 4
            },
            {
                name: "Magmortar",
                description: "It expels fire from its arms with explosive power.",
                height: 1.6,
                weight: 68.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/magmortar.png",
                pokedex_id: 467,
                type1: 1,
                type2: null,
                generation: 4
            },
            {
                name: "Togekiss",
                description: "It spreads happiness and fortune, flying gracefully with its wings.",
                height: 1.5,
                weight: 38.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/togekiss.png",
                pokedex_id: 468,
                type1: 17,
                type2: 9,
                generation: 4
            },
            {
                name: "Yanmega",
                description: "It flies at high speeds and strikes prey with precision.",
                height: 1.9,
                weight: 51.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/yanmega.png",
                pokedex_id: 469,
                type1: 9,
                type2: 5,
                generation: 4
            },
            {
                name: "Leafeon",
                description: "It evolves near lush foliage and absorbs nutrients from plants.",
                height: 1.0,
                weight: 25.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/leafeon.png",
                pokedex_id: 470,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Glaceon",
                description: "It evolves in cold environments and controls ice around it.",
                height: 0.8,
                weight: 25.9,
                region_id: 4,
                image: "http://localhost:3000/uploads/glaceon.png",
                pokedex_id: 471,
                type1: 5,
                type2: null,
                generation: 4
            },
            {
                name: "Gliscor",
                description: "It glides using its wings and attacks with sharp claws.",
                height: 2.0,
                weight: 42.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/gliscor.png",
                pokedex_id: 472,
                type1: 8,
                type2: 9,
                generation: 4
            },
            {
                name: "Mamoswine",
                description: "It charges enemies with its massive tusks and runs swiftly.",
                height: 2.5,
                weight: 291.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/mamoswine.png",
                pokedex_id: 473,
                type1: 8,
                type2: 5,
                generation: 4
            },
            {
                name: "Porygon-Z",
                description: "It has a highly irregular body and moves unpredictably in cyberspace.",
                height: 0.9,
                weight: 34.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/porygonz.png",
                pokedex_id: 474,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Gallade",
                description: "It protects its trainer with psychic blades from its elbows.",
                height: 1.6,
                weight: 52.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/gallade.png",
                pokedex_id: 475,
                type1: 6,
                type2: 10,
                generation: 4
            },
            {
                name: "Probopass",
                description: "It uses its nose magnet to detect threats and attract metallic objects.",
                height: 1.4,
                weight: 340.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/probopass.png",
                pokedex_id: 476,
                type1: 16,
                type2: 12,
                generation: 4
            },
            {
                name: "Dusknoir",
                description: "It carries spirits to the afterlife using its shadowy body.",
                height: 2.2,
                weight: 106.6,
                region_id: 4,
                image: "http://localhost:3000/uploads/dusknoir.png",
                pokedex_id: 477,
                type1: 13,
                type2: null,
                generation: 4
            },
            {
                name: "Froslass",
                description: "It is said to freeze people who wander into snowy mountains.",
                height: 1.3,
                weight: 26.6,
                region_id: 4,
                image: "http://localhost:3000/uploads/froslass.png",
                pokedex_id: 478,
                type1: 5,
                type2: 13,
                generation: 4
            },
            {
                name: "Rotom",
                description: "It can inhabit electronic devices and change forms.",
                height: 0.3,
                weight: 0.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/rotom.png",
                pokedex_id: 479,
                type1: 4,
                type2: 13,
                generation: 4
            },
            {
                name: "Uxie",
                description: "It represents knowledge and can erase memories of humans.",
                height: 0.3,
                weight: 0.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/uxie.png",
                pokedex_id: 480,
                type1: 10,
                type2: null,
                generation: 4
            },
            {
                name: "Mesprit",
                description: "It represents emotion and can communicate feelings to humans.",
                height: 0.3,
                weight: 0.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/mesprit.png",
                pokedex_id: 481,
                type1: 10,
                type2: null,
                generation: 4
            },
            {
                name: "Azelf",
                description: "It represents willpower and inspires humans to achieve great things.",
                height: 0.3,
                weight: 0.3,
                region_id: 4,
                image: "http://localhost:3000/uploads/azelf.png",
                pokedex_id: 482,
                type1: 10,
                type2: null,
                generation: 4
            },
            {
                name: "Dialga",
                description: "It controls time and can bend it to its will.",
                height: 5.4,
                weight: 683.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/dialga.png",
                pokedex_id: 483,
                type1: 16,
                type2: 14,
                generation: 4
            },
            {
                name: "Palkia",
                description: "It governs space and can distort dimensions.",
                height: 4.2,
                weight: 336.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/palkia.png",
                pokedex_id: 484,
                type1: 2,
                type2: 14,
                generation: 4
            },
            {
                name: "Heatran",
                description: "It lives in volcanic areas and controls magma and fire.",
                height: 1.7,
                weight: 430.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/heatran.png",
                pokedex_id: 485,
                type1: 1,
                type2: 16,
                generation: 4
            },
            {
                name: "Regigigas",
                description: "It can move continents and commands legendary Pokémon.",
                height: 3.7,
                weight: 420.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/regigigas.png",
                pokedex_id: 486,
                type1: 18,
                type2: null,
                generation: 4
            },
            {
                name: "Giratina",
                description: "It lives in the Distortion World and controls antimatter.",
                height: 4.5,
                weight: 750.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/giratina.png",
                pokedex_id: 487,
                type1: 13,
                type2: 14,
                generation: 4
            },
            {
                name: "Cresselia",
                description: "It represents the crescent moon and brings pleasant dreams.",
                height: 1.5,
                weight: 85.6,
                region_id: 4,
                image: "http://localhost:3000/uploads/cresselia.png",
                pokedex_id: 488,
                type1: 17,
                type2: null,
                generation: 4
            },
            {
                name: "Phione",
                description: "It swims freely in the ocean and is said to bring happiness.",
                height: 0.4,
                weight: 3.1,
                region_id: 4,
                image: "http://localhost:3000/uploads/phione.png",
                pokedex_id: 489,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Manaphy",
                description: "It can bond with any Pokémon and has the ability to thrive in oceans.",
                height: 0.3,
                weight: 1.4,
                region_id: 4,
                image: "http://localhost:3000/uploads/manaphy.png",
                pokedex_id: 490,
                type1: 2,
                type2: null,
                generation: 4
            },
            {
                name: "Darkrai",
                description: "It creates nightmares and lurks in darkness.",
                height: 1.5,
                weight: 50.5,
                region_id: 4,
                image: "http://localhost:3000/uploads/darkrai.png",
                pokedex_id: 491,
                type1: 15,
                type2: null,
                generation: 4
            },
            {
                name: "Shaymin",
                description: "It absorbs nutrients from the soil and purifies the land it inhabits.",
                height: 0.2,
                weight: 2.1,
                region_id: 4,
                image: "http://localhost:3000/uploads/shaymin.png",
                pokedex_id: 492,
                type1: 3,
                type2: null,
                generation: 4
            },
            {
                name: "Arceus",
                description: "It is said to have created the Pokémon universe.",
                height: 3.2,
                weight: 320.0,
                region_id: 4,
                image: "http://localhost:3000/uploads/arceus.png",
                pokedex_id: 493,
                type1: 18,
                type2: null,
                generation: 4
            }
        ]

        for (let pokemon of poke) {
            await pool.query(`
                INSERT INTO pokemon (name, description, height, weight, region_id, image, pokedex_id, type1, type2, generation) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT (name) DO NOTHING`,
                [pokemon.name, pokemon.description, pokemon.height, pokemon.weight, pokemon.region_id, pokemon.image, pokemon.pokedex_id, pokemon.type1, pokemon.type2, pokemon.generation])
        }

        console.log("Berhasil Membuat Pokemon Gen 4")
    }
    catch (err) {
        console.log(err.message)
    }
}

module.exports = pokemonGen4Seeder