const pool = require("../../db")

async function evolutionGen1Seeder() {
    try {
        const evolutions = [
            { pre_stage: 1, post_stage: 2, method: "Level 16" },
            { pre_stage: 2, post_stage: 3, method: "Level 32" },
            { pre_stage: 4, post_stage: 5, method: "Level 16" },
            { pre_stage: 5, post_stage: 6, method: "Level 36" },
            { pre_stage: 7, post_stage: 8, method: "Level 16" },
            { pre_stage: 8, post_stage: 9, method: "Level 36" },
            { pre_stage: 10, post_stage: 11, method: "Level 7" },
            { pre_stage: 11, post_stage: 12, method: "Level 10" },
            { pre_stage: 13, post_stage: 14, method: "Level 7" },
            { pre_stage: 14, post_stage: 15, method: "Level 10" },
            { pre_stage: 16, post_stage: 17, method: "Level 18" },
            { pre_stage: 17, post_stage: 18, method: "Level 36" },
            { pre_stage: 19, post_stage: 20, method: "Level 20" },
            { pre_stage: 21, post_stage: 22, method: "Level 20" },
            { pre_stage: 23, post_stage: 24, method: "Level 22" },
            { pre_stage: 172, post_stage: 25, method: "High Friendship"},
            { pre_stage: 25, post_stage: 26, method: "Thunder Stone" },
            { pre_stage: 27, post_stage: 28, method: "Level 22" },
            { pre_stage: 29, post_stage: 30, method: "Level 16" },
            { pre_stage: 30, post_stage: 31, method: "Moon Stone" },
            { pre_stage: 32, post_stage: 33, method: "Level 16" },
            { pre_stage: 33, post_stage: 34, method: "Moon Stone" },
            { pre_stage: 173, post_stage: 35, method: "High Friendship" },
            { pre_stage: 35, post_stage: 36, method: "Moon Stone" },
            { pre_stage: 37, post_stage: 38, method: "Fire Stone" },
            { pre_stage: 174, post_stage: 39, method: "High Friendship" },
            { pre_stage: 39, post_stage: 40, method: "Moon Stone" }, 
            { pre_stage: 41, post_stage: 42, method: "Level 22" },
            { pre_stage: 42, post_stage: 169, method: "High Friendship" },
            { pre_stage: 43, post_stage: 44, method: "Level 21" },
            { pre_stage: 44, post_stage: 45, method: "Leaf Stone" },
            { pre_stage: 44, post_stage: 182, method: "Sun Stone" },
            { pre_stage: 46, post_stage: 47, method: "Level 24" },
            { pre_stage: 48, post_stage: 49, method: "Level 31" },
            { pre_stage: 50, post_stage: 51, method: "Level 26" },
            { pre_stage: 52, post_stage: 53, method: "Level 28" },
            { pre_stage: 54, post_stage: 55, method: "Level 33" },
            { pre_stage: 56, post_stage: 57, method: "Level 28" },
            { pre_stage: 58, post_stage: 59, method: "Fire Stone" },
            { pre_stage: 60, post_stage: 61, method: "Level 25" },
            { pre_stage: 61, post_stage: 62, method: "Water Stone" },
            { pre_stage: 61, post_stage: 186, method: "Trade hold Kings Rock" },
            { pre_stage: 63, post_stage: 64, method: "Level 16" },
            { pre_stage: 64, post_stage: 65, method: "Trade" },
            { pre_stage: 66, post_stage: 67, method: "Level 28" },
            { pre_stage: 67, post_stage: 68, method: "Trade" },
            { pre_stage: 69, post_stage: 70, method: "Level 21" },
            { pre_stage: 70, post_stage: 71, method: "Leaf Stone" },
            { pre_stage: 72, post_stage: 73, method: "Level 30" },
            { pre_stage: 74, post_stage: 75, method: "Level 25" },
            { pre_stage: 75, post_stage: 76, method: "Trade" },
            { pre_stage: 77, post_stage: 78, method: "Level 40" },
            { pre_stage: 79, post_stage: 80, method: "Level 37" },
            { pre_stage: 79, post_stage: 199, method: "Trade hold Kings Rock" },
            { pre_stage: 81, post_stage: 82, method: "Level 30" },
            { pre_stage: 82, post_stage: 462, method: "Thunder Stone Or Level Up in a Magnetic Field Area" },
            { pre_stage: 84, post_stage: 85, method: "Level 31" },
            { pre_stage: 86, post_stage: 87, method: "Level 34" },
            { pre_stage: 88, post_stage: 89, method: "Level 38" },
            { pre_stage: 90, post_stage: 91, method: "Water Stone" },
            { pre_stage: 92, post_stage: 93, method: "Level 25" },
            { pre_stage: 93, post_stage: 94, method: "Trade" },
            { pre_stage: 95, post_stage: 208, method: "Trade hold Metal Coat" },
            { pre_stage: 96, post_stage: 97, method: "Level 26" },
            { pre_stage: 98, post_stage: 99, method: "Level 28" },
            { pre_stage: 100, post_stage: 101, method: "Level 30" },
            { pre_stage: 102, post_stage: 103, method: "Leaf Stone" },
            { pre_stage: 104, post_stage: 105, method: "Level 28" },
            { pre_stage: 236, post_stage: 106, method: "Level 20, Atk > Deff" },
            { pre_stage: 236, post_stage: 107, method: "Level 20, Atk < Deff" },
            { pre_stage: 108, post_stage: 463, method: "Learn Rollout" },
            { pre_stage: 109, post_stage: 110, method: "Level 35" },
            { pre_stage: 111, post_stage: 112, method: "Level 42" },
            { pre_stage: 112, post_stage: 464, method: "Trade hold Protector" },
            { pre_stage: 440, post_stage: 112, method: "Daytime hold Oval Stone" },
            { pre_stage: 113, post_stage: 242, method: "Friendship" },
            { pre_stage: 114, post_stage: 465, method: "Learn Ancient Power" },
            { pre_stage: 116, post_stage: 117, method: "Level 32" },
            { pre_stage: 117, post_stage: 230, method: "Trade hold Dragon Scale" },
            { pre_stage: 118, post_stage: 119, method: "Level 33" },
            { pre_stage: 120, post_stage: 121, method: "Water Stone" },
            { pre_stage: 439, post_stage: 122, method: "Learn Mimic" },
            { pre_stage: 123, post_stage: 212, method: "Trade hold Metal Coat" },
            { pre_stage: 238, post_stage: 124, method: "Level 30" },
            { pre_stage: 239, post_stage: 125, method: "Level 30" },
            { pre_stage: 125, post_stage: 466, method: "Trade hold Electivire" },
            { pre_stage: 240, post_stage: 126, method: "Level 30" },
            { pre_stage: 126, post_stage: 467, method: "Trade hold Magmarizer" },
            { pre_stage: 129, post_stage: 130, method: "Level 20" },
            { pre_stage: 133, post_stage: 134, method: "Water Stone" },
            { pre_stage: 133, post_stage: 135, method: "Thunder Stone" },
            { pre_stage: 133, post_stage: 136, method: "Fire Stone" },
            { pre_stage: 137, post_stage: 233, method: "Trade hold Upgrade" },
            { pre_stage: 138, post_stage: 139, method: "Level 40" },
            { pre_stage: 140, post_stage: 141, method: "Level 40" },
            { pre_stage: 446, post_stage: 143, method: "Friendship" },
            { pre_stage: 147, post_stage: 148, method: "Level 30" },
            { pre_stage: 148, post_stage: 149, method: "Level 55" }
        ]

        for (let evol of evolutions) {
            await pool.query(`
                INSERT INTO evolution (pre_stage, post_stage, method) VALUES ($1, $2, $3)`,
                [evol.pre_stage, evol.post_stage, evol.method])
        }

        console.log("Berhasil Membuat Evolution Pokemon Gen 1")
    }
    catch (err) {
        console.log("Gagal, ", err.message)
    }
}

module.exports = evolutionGen1Seeder